### ISSUE TITLE
 When big msg is transmitted, it will lead to high memory usage of the legacy STL.

### ISSUE THREAD

**Issue by KanonWY** [eclipse-ecal/ecal#1021]
### How Found
When use the example (datarate_rec/datarate_snd) , I found some question(maybe). 
For datarate_snd, I set the msg' length to 200Mib and  remove the sleep function in the loop. 
For datarate_rec, I alse remove the sleep function in the loop. Then I run them. Of course, the above operation will cause extremely high load. After a few seconds or so, we'll see memory spike on the receiving side, and then stop the sending side(otherwise the receiver would OOM).
### observed situation
After performing the above operations, the receiver program will consume a lot of memory, and it will always occupy it if it is not stopped.
While running the program, I noticed some logs appearing on both ends.
```bash
Could not lock memory file mutex: topic_107489272315_shm.
```
After read source code,  this is due to the slow response, re-creating a new shared memory file. 
I'm wondering about the high memory usage on the receiving end, because I understand from the [official documentation](https://eclipse-ecal.github.io/ecal/advanced/message_drops.html) that dropping messages on the receiving end is allowed. But why does the receiving end have such a high memory consumption (even being OOM).[Even if my example code is not normal this should not happen]
### What I Try
I tried linking to the executable using `tcmalloc` and then using the pprof tool to see memory allocations.I found out that the internal high memory consumption is in a STL object(in the code block below) which accounts for almost 99%.
```c++
class CMemFileObserver
{
      std::vector<char> m_ecal_buffer;
};
```
Since I transferred a large amount of data, the capacity of this data structure is 200M(but But the receiving end left over G memory). So I continued to dig into the source code, I noticed that each shared memory corresponds to a `CMemFileObserver` which is managed by `CMemFileThreadPool`. This means that the creation of a new shared memory file will be tracked by a new CMemFileObserver object.  Since we recreated many of the shared memory, Although each shared memory file is released, the expired `CMemFileObserver` object has not been recycled. I noticed that `CMemFileThreadPool::CleanupPool` is never called (There was a call that was removed two years ago.)
```cpp
  bool CMemFileThreadPool::ObserveFile(const std::string& memfile_name_, const std::string& memfile_event_, const std::string& topic_name_, const std::string& topic_id_, int timeout_observation_ms, const MemFileDataCallbackT& callback_)
  {
    if(!m_created)            return(false);
    if(memfile_name_.empty()) return(false);

    // remove outdated observers
    //CleanupPool();
    ......
}
```
Since the `CMemFileObserver` has not been cleaned up, the object always exists at the receiving end, and the `m_ecal_buffer` in this object is very large, which indirectly causes the memory at the receiving end to remain high.
### My Temporary solution
Finally, when the `CMemFileObserver` thread exits, I clear the capacity of m_ecal_buffer to 0, which temporarily solves the problem of excessive memory remaining.
```cpp
//ecal_memfile_pool.cpp:263
void CMemFileObserver::Observe(...)
{
    .....
    
    //try to clear the capacity.
    //shrink_to_fit way
    //m_ecal_buffer.resize(0);
    //m_ecal_buffer.shrink_to_fit();
    // swap way
    //std::vector<char> empty_vector;
    //std::swap(empty_vector, m_ecal_buffer)

    // mark as stopped
    m_is_observing = false; //-V1020
}
```
Is there a better way to solve this problem, or is the problem I'm raising just because of poor use of the application layer? (I think that this kind of memory explosion cannot be tolerated even if the application layer is used incorrectly)

Finally, thanks to your team for open-sourcing the excellent C++ code for us to learn from.

### How to reproduce

1. Just in master source code, compile.(Ubuntu20.04, gcc9, cmake3.25, ninja1.10.0)
2.  Modify the `datarate_rec/datarate_snd` source code according to the above method to reproduce.
```cpp
//datarate_rec.cpp
// delete sleep function
  while (eCAL::Ok())
  {
    // sleep 100 ms
//    std::this_thread::sleep_for(std::chrono::milliseconds(100));
 }
```
```cpp
//datarate_snd.cpp
// send 200M
  while(eCAL::Ok())
  {
    // send content
    pub.Send(send_s);
    // sleep
//    std::this_thread::sleep_for(std::chrono::milliseconds(sleep));
  }
```

### How did you get eCAL?

Custom Build / Built from source

### Environment

- ecal Version: Source Code Compile(about two days age)
- Operation System: Ubuntu20.04
- Python Version(Python 2.7.18, Python 3.8.10)
- cmake: 3.25
- gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- ninja1.10.0

**Comment by rex-schilasky** [comment]
Hi @KanonWY,

first of all - GREAT ISSUE feedback, thank you.

We are now working on it. The issue needs to fix at least on two places:

1. free the memory if the observing thread finished
2. call `CleanupPool` periodically to remove finished observers from the global pool

Your suggested change will for sure fix part 1. I assume you used the `swap` approach to force the freeing of the memory.

**Comment by KanonWY** [comment]
Hi @rex-schilasky ,
Thank you for being effective.
For the second and third part, I also think there may be a better way to solve it, if so, please let me know in time.I will keep track of this project.

**Comment by rex-schilasky** [comment]
Hi @KanonWY,

one more question. What did you intend with that ?

```cpp
//datarate_rec.cpp
// delete sleep function
  while (eCAL::Ok())
  {
    // sleep 100 ms
//    std::this_thread::sleep_for(std::chrono::milliseconds(100));
 }
```

This change will just increase your CPU load for the receiving application but not improve the performance (rather decrease it).
 
I will add an additional command line parameter for the `datarate_snd` sample application to set the shared memory handshake acknowledgement timeout (default = 0, that means no handshake from subscriber back to publisher). Using this parameter you can ensure to transfer your large messages without dropping.

**Comment by KanonWY** [comment]
Hi @rex-schilasky,
I only did this operation to test the limit boundary and it has no special significance.(After deleting the sleep function, the main thread will interrupt its operation after the time slice runs out, thus strengthening the competition with other worker threads.)
This new parameter is very good. I have noticed that this [option](https://eclipse-ecal.github.io/ecal/advanced/layers/shm.html#transport-layer-shm-memfile-ack) is also included in the ecal.ini configuration file.
