### ISSUE TITLE
can't subscribe the datas from BUS, if the ecal system time occurred dramatic vibration

### ISSUE THREAD

**Issue by sainttelant** [eclipse-ecal/ecal#1034]
### Problem Description

the modules i deployed with ecal usually cannot subscribe the datas subscribed from other topics!
the details are as follows: 
the system time usually was modified  to the year of 1970 caused by some uncertain reasons, probably resulted from ntp sync mechanism in program design.  And the time will be fixed up after approximately 60 seconds, and then, the ecal getsystemtime function will get the current time, and this probably leads to the issue which cannot subscribe the datas from the other publisher.   I am not sure whether this issue could happen in some circumstance, or this is only the mechanism of eCal design.

my Ecal version is 5.9.10

### How to reproduce

1. use ntpdate command to force the system time to rollback the year of 2021.1.1
2.  the every progress applications still run in the system
3.  however, the submodule cannot subscribe the datas from other running publisher(i still observe the datas still publish at real time)

### How did you get eCAL?

Ubuntu PPA (apt-get)

### Environment

Ecal: v5.9.10   linux version 4.14.98    arch64

**Comment by rex-schilasky** [comment]
Hi, I remember well that we fixed that issue. Are you able to update to an up to date eCAL 5.11.x ?

**Comment by sainttelant** [comment]
@rex-schilasky all right, i will try to upgrade the ecal version to 5.11.X, and observe it whether the issue is solved. thanks a lot

**Comment by FlorianReimold** [comment]
Closing, as this has probably been fixed. Please reopen, if that proves to be wrong.
