### ISSUE TITLE
Correct check for nullptr?

### ISSUE THREAD

**Issue by KerstinKeller** [eclipse-ecal/ecal#1036]
https://github.com/eclipse-ecal/ecal/blob/be6cccd65fc93bce31811e5e67d9437ae17db9c1/ecal/core/src/ecalc.cpp#L76-L83

shouldn't this be:

```
 if((major_ == nullptr) || (minor_ == nullptr) || (patch_ == nullptr)) return(-1); 
```

**Comment by FlorianReimold** [comment]
yes, it probably should

**Comment by FlorianReimold** [comment]
@KerstinKeller: Is there a reason why you created an issue with the correct code, but didn't actually fix it?

**Comment by KerstinKeller** [comment]
Well I was actually looking for something else, and stumbled upon it. So I made an issue in order not to forget about it.
