### ISSUE TITLE
If memfile_buffer_count != 0, first messages are lost

### ISSUE THREAD

**Issue by KerstinKeller** [eclipse-ecal/ecal#1074]
### Problem Description

With a higher `memfile_buffer_count`, not all messages reach the subscriber, see the testcase in this commit:
https://github.com/eclipse-ecal/ecal/compare/master...hotfix/shm-buffer-count-testcase

### How to reproduce

Run the provided testcase.

### How did you get eCAL?

I don't know

### Environment

Current master

**Comment by chengguizi** [comment]
Any update on this so far? Not sure how this would be affected by the major zero-copy change in #1082 

Having a circular buffer of memfiles + zero copy would be a really great feature to have for low-latency, high-frequency, low-drop message system.

**Comment by rex-schilasky** [comment]
@chengguizi this fix is in progress and will be part of 5.12.

**Comment by chengguizi** [comment]
Sounds good! Very look forward to an improved zero-copy implementation that also supports circular buffer (hence avoid missing messages) :)
