### ISSUE TITLE
Add mocking support to eCAL Protobuf for testing

### ISSUE THREAD

**Issue by parsley72** [eclipse-ecal/ecal#1107]
### Context

I'd like to be able to mock eCAL APIs based on Protobuf.

### Proposal

Recorder and Player allow you to record and playback eCAL topics. But they don't allow you to mock APIs for automated testing.

Postman and other tools already support this functionality for gRPC:
https://blog.postman.com/postman-mocking-magic-for-grpcs/

**Comment by parsley72** [comment]
Similar to the link, you should be able to:
1. Import Protobuf file(s).
2. Run a server that mocks these services.
3. Have them either return random values or be able to specify them.

You can use this either during development of a new service or mock an existing one for automated testing.

**Comment by KerstinKeller** [comment]
It sounds like you don't actually want to "mock" anything, but rather have a template that can generate sample applications for you, based on a given set of protobuf files?

If so, I guess that could be helpful to have a code generator, to autogenerate Publish / Subscribe / Client / Server samples.

**Comment by parsley72** [comment]
Maybe we have a different understanding of the word "mock"? I used Postman as an example but there are many other gRPC mocking tools, for instance https://github.com/tokopedia/gripmock. All I want to do is the same as what these tools provide but for eCAL instead of gRPC.
