### ISSUE TITLE
How to communicate between arm architecture and x86 architecture？

### ISSUE THREAD

**Issue by FanZhang91** [eclipse-ecal/ecal#1125]
### Problem Description

I want to use eCAL to achieve communication between different architectures(aarch64 and x86). I follow the guide to configure cloud mode, but I just find they can't communite with eath other(two machines of the same x86 architecture can make normal communication)。I use offical sample(ecal_sample_minimal_snd/ecal_sample_minimal_rec) to test and here is more details:
             version: eCAL 5.10.3
             publish host machine: aarch64 ubuntu 18.04
             subscribe host machine: x86 windows10

![IMG_20230612_150858](https://github.com/eclipse-ecal/ecal/assets/21361349/0ec9d0ed-3a26-4242-a827-12e3be0ecff6)
![IMG_20230612_150944](https://github.com/eclipse-ecal/ecal/assets/21361349/0bf8ae07-8e2b-40fb-be5f-fecb18dcfba5)

### How to reproduce

[https://eclipse-ecal.github.io/ecal/getting_started/cloud.html](url)

### How did you get eCAL?

Ubuntu PPA (apt-get)

### Environment

eCAL:5.10.3

**Comment by FlorianReimold** [comment]
Can you please follow the following 2 documentation pages:

1. https://eclipse-ecal.github.io/ecal/getting_started/cloud.html
2. https://eclipse-ecal.github.io/ecal/getting_started/services.html#hostname-resolution

The please post your network configuration (ipconfig / ifconfig) as well as route configuration (route -n / route print)
