### ISSUE TITLE
Linking issue on windows LNK2019

### ISSUE THREAD

**Issue by windelbouwman** [eclipse-ecal/ecal#1137]
### Problem Description

I try to build a C++ minimal example with the ecal release for windows.

The installation worked, and I tried the python example. Trying to build a simple C++ demo gives me the following error:

```
main2.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class google::protobuf::FileDescriptorProto const & __cdecl google::protobuf::FileDescriptorSet::file(int)const " (__imp_?file@FileDescriptorSet@protobuf@google@@QEBAAEBVFileDescriptorProto@23@H@Z) referenced in function "bool __cdecl eCAL::protobuf::HasFile(class google::protobuf::FileDescriptorSet const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?HasFile@protobuf@eCAL@@YA_NAEBVFileDescriptorSet@1google@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
```

This is my cmake file:

```

cmake_minimum_required(VERSION 3.16)

project(helloworld VERSION 1.0.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(eCAL REQUIRED)
find_package(Protobuf REQUIRED)

set(protobuf_files
    ${CMAKE_CURRENT_SOURCE_DIR}/status.proto
)
protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS ${protobuf_files})

include_directories(${CMAKE_CURRENT_BINARY_DIR})
add_executable(
    helloworld2
    main2.cpp
    ${PROTO_SRCS} ${PROTO_HDRS}
)
target_link_libraries(
    helloworld2
    PRIVATE
    eCAL::core
    protobuf::libprotobuf
)

```

This is my example:
```

#include <ecal/ecal.h>
#include <ecal/msg/string/publisher.h>
#include <ecal/msg/protobuf/publisher.h>
#include <ecal/msg/protobuf/subscriber.h>

#include "status.pb.h"

#include <iostream>
#include <thread>

int main(int argc, char *argv[])
{
    eCAL::Initialize(argc, argv, "Hello World Publisher");
    eCAL::protobuf::CSubscriber<proto_messages::HelloWorld> m_subscriber("TESTTOPIC");
    eCAL::Finalize();
    return 0;
}

```

### How to reproduce

mkdir build
cd build
cmake -G Ninja ..
ninja

### How did you get eCAL?

Download from Release Page

### Environment

- OS: Windows
- eCAL:  5.11.4
- MSVC: MSVC 19.29.30147.0

**Comment by windelbouwman** [comment]
Thank you, that fixed my build.

The problem I ran into next is that the cmake function `protobuf_generate_cpp` is not present when setting this variable.

It would be neat if the `find_package` cmake command would work regardless of this global cmake option. Is there an issue for this?

**Comment by FlorianReimold** [comment]
The protobuf_generate_cpp is a kind-of-deprecated quick and dirty function that a cmake developer coded themself. Google provides a much more sophisticated function.

You have the options to:
1. Use the `PROTOBUF_TARGET_CPP` function from eCAL (see documentation) https://eclipse-ecal.github.io/ecal/getting_started/hello_world_proto.html
2. Set the `protobuf_MODULE_COMPATIBLE` variable before finding protobuf to get the legacy `protobuf_generate_cpp` function from the protobuf-config.cmake. Be aware that you also get all the issues it has with subdirectories. In my experience this function is actually not 100% compatible to the cmake protobuf_target_cpp function, so if you implemented workarounds for the issue of protobuf_generate_cpp, those workaround may not work anymore.
3. Use the offical `protobuf_generate` function by google: https://github.com/protocolbuffers/protobuf/blob/main/docs/cmake_protobuf_generate.md
    I don't have much experience with this, as in eCAL we still rely on our own `PROTOBUF_TARGET_CPP`, but I would still go with option for external projects, to be honest. I think using the offical protobuf generate function from google should be the proper solution. This is also the most versatile solution, as it also supports different languages and custom protoc plugins.
