### ISSUE TITLE
Document eCAL 5.12 Features

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#1145]
We need to document some newly introduced features:
- Zero Copy
  - [X] Document Zero Copy Feature @FlorianReimold @rex-schilasky 
  - [X] Add Doxygen Documentation for `CPayloadWriter` @rex-schilasky 
  - [X] CPlayload for the Publisher for 5.12. We should write a section on it in the documentation, especially for end users who have their own publishers. @rex-schilasky @KerstinKeller 
  - [X]  zero copy functionality available if there is only local communication. @rex-schilasky @KerstinKeller 
- [x] Host group feature (maybe modify [docker tutorial](https://eclipse-ecal.github.io/ecal/advanced/ecal_in_docker.html)) @hannemn @KaanConti 
- Release Documentation (Branch started here: [feature/doc_5_12](https://github.com/eclipse-ecal/ecal/tree/feature/doc_5_12/))
  - [x] Changelog
  - [x] Highlights
  - [ ] Screenshot / Graphic
  - [x] Compatibility Table

**Comment by FlorianReimold** [comment]
Some doc is here and can probably be copied:
https://github.com/eclipse-ecal/ecal/pull/1082

**Comment by g-tejas** [comment]
Is there a summary of API breaking changes somewhere, like a changelog? Thanks!

**Comment by FlorianReimold** [comment]
We are still working on it and will be publishing it, soon. But there won't be any API breaks. The API got extended with new functions, but nothing old was removed, so it is downwards compatible.
