### ISSUE TITLE
ZeroCopy + Multibuffering leads to inconsitent data

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#1163]
### Problem Description

Let's say we have 3 buffers for the same topic:
- 0000
- 0000
- 0000

We now write a 1 at pos 1. We expect a [1000] being published
- 1000 < gets published
- 0000
- 0000

We now write a 1 at pos2. We exepct a [1100] being published
- 1000
- 0100 < gets published
- 0000

So at the moment, multibuffering + zerocopy leads to inconsistent data.

### How to reproduce

This was a theoretical discussion.

### How did you get eCAL?

Other

### Environment

- eCAL 5.12.0-rc.1 / master

**Comment by chengguizi** [comment]
Hi @FlorianReimold  I don't quite get the issue. Do your 3 buffers mean the three slots in the ring buffer?

If yes, when we are still writing to the first slot, from the publisher, isn't the slot protected from any readings from subscriber? Only when that slot of data is fully populated, then it is released for reading.

Yes, I do want to get more insights to multibuffering / ring buffer.

**Comment by FlorianReimold** [comment]
- Yes, I am referring to the SHM Multibuffering feature that works as a ring buffer
- Yes, memory files are protected while writing
- Multi Buffering feature creates multiple SHM files that are used one after another. This works perfectly when you always write the entire message to it. If you however only write a parts of the message, the second SHM file will not automatically reflect the changes you made before. 

In the currently unreleased dev version, this bug exists, as we have added the Zerocopy publishing feature. It didn't exist in 5.11, as that version didn't have the Zero Copy publishing.

You can learn more about the Multi Buffering feature in the Documentation:
https://eclipse-ecal.github.io/ecal/advanced/layers/shm.html#multi-buffering-mode-optional

**Comment by chengguizi** [comment]
Yes for sure! I saw the 5.12 is already in RC stage, which means API freeze. We would like to start trying on our development builds! 
Would this be the branch to try? https://github.com/eclipse-ecal/ecal/tree/support/v5.12

**Comment by FlorianReimold** [comment]
Yes, you can use that branch. Or, if you want a more precise git tag, you can use the rc.1tag directly:
https://github.com/eclipse-ecal/ecal/releases/tag/v5.12.0-rc.1
