### ISSUE TITLE
Weird CMake Bug with WSL

### ISSUE THREAD

**Issue by Blutkoete** [eclipse-ecal/ecal#1195]
### Problem Description

I wanted to compile eCAL in an Ubuntu 22.04 WSL environment and experienced a weird CMake bug. It only happens if I have eCAL installed via the installer in Windows and added the binaries to the path.

Windows adds all paths from the user's Windows environment to the end of the Ubuntu PATH variable:

![grafik](https://github.com/eclipse-ecal/ecal/assets/26028813/812b8489-4016-4f98-a7ed-71073357c6d0)

If I now run _cmake -S . -B \_build_ in WSL, it errors out for HDF5 (build HDF5 is set to OFF and HDF5 is installed in WSL) because it picks up the CMake config for HDF5 from _/mnt/c/Werkbank/Tools/eCAL/cmake_:

![grafik](https://github.com/eclipse-ecal/ecal/assets/26028813/00dbc214-56aa-49d7-8feb-fe7ab8e37649)

A quick workaround is to either rename that folder from "cmake" to "cmake_" or to remove _/mnt/c/Werkbank/Tools/eCAL/bin_ from the path within WSL.

So it appears that somewhere in the CMake configuration chain, a CMake file looks through my PATH variables, detects something in _/mnt/c/Werkbank/Tools/eCAL/bin_ and based on that decides to add _/mnt/c/Werkbank/Tools/eCAL/cmake_ to the CMake module path!

While this is for sure not an officially supported setup and a simple workaround exists, I'd still like to mention it because it means that something in the chain is trying to automagically find a package and does it wrong. I tried to grep myself thorugh the CMake files and look for stuff like "find_file" or "find_library", but until now I wasn't really successful and I'm not a CMake expert.

Before I waste hours trying to figure out who is the culprit, I wanted to ask if you maybe know some place where you are doing something like that? Maybe looking for some eCAL core DLLs and then adding "../cmake" to the CMake lookup path? Or do you have any other ideas what the reason for this behaviour might be?

### How to reproduce

1. Install eCAL in Windows via the installer, adding the binaries to your Windows path
2. Clone eCAL into WSL
3. Install needed dependencies for a eCAL Ubuntu build
4. Run cmake

### How did you get eCAL?

Custom Build / Built from source

### Environment

- eCAL 5.11.4 on Windows 11
- eCAL master head in WSL (Ubuntu 22.04)

**Comment by KerstinKeller** [comment]
Hi, thanks for reporting.
I think we set a registry variable in the installer, which causes CMake to search the ecal install path (for user convenience).
However, quite inconvenient that this is picked up from within WSL 🤔

Maybe this is something that should be reported to CMake, I'm not quite sure...

(although I introduced this behavior, I am no longer a fan. It can lead to side effects such as the one that you described).
