### ISSUE TITLE
In eCAL communication where UDP and TCP coexist, there is an issue where, after a prolonged disconnection in a local area network, communication cannot be established upon reconnecting.

### ISSUE THREAD

**Issue by tanshengjiang** [eclipse-ecal/ecal#1205]
### Problem Description

Two computers are communicating via eCAL, with eCAL using UDP as the default transport protocol. For handling large data, a TCP API interface has been integrated. This setup enables eCAL communication within a local area network with both UDP and TCP coexisting.  However, there's a specific issue: when both computers start the program simultaneously, the publish-subscribe communication works fine. But if one computer starts the program, and the other computer begins the program after a delay of around ten minutes, communication fails. However, if the second computer restarts the program, communication is reestablished.  How can this problem be resolved?

### How to reproduce

    // image publisher is SHM
    img_publisher_.SetLayerMode(eCAL::TLayer::tlayer_udp_mc, eCAL::TLayer::smode_off);
    img_publisher_.SetLayerMode(eCAL::TLayer::tlayer_tcp, eCAL::TLayer::smode_off);
    // image compressed publisher is TCP
    img_compressed_publisher_.SetLayerMode(eCAL::TLayer::tlayer_udp_mc, eCAL::TLayer::smode_off);
    img_compressed_publisher_.SetLayerMode(eCAL::TLayer::tlayer_tcp, eCAL::TLayer::smode_auto);

    img_publisher_ = eCAL::protobuf::CPublisher<SensorMsg::Image>(config_.image_topic);
    img_compressed_publisher_ = eCAL::protobuf::CPublisher<SensorMsg::ImageCompressed>(config_.image_compressed_topic);

### How did you get eCAL?

Ubuntu PPA (apt-get)

### Environment

5.11.4
Ubuntu 18.04
cmake_minimum_required(VERSION 2.8.12)

**Comment by FlorianReimold** [comment]
Hi @tanshengjiang,

I tried to reproduce your issue as follows:

- I set up 2 Ubuntu 18.04 machines
- I installed eCAL 5.11 from the PPA (it's 5.11.5 though)
- I started `ecal_sample_person_snd_tcp` on one machine
- I waited 10 minutes
- I started `ecal_sample_person_rec` on the other machine

It worked immediately as one would expect. 

![image](https://github.com/eclipse-ecal/ecal/assets/11774314/60ee31e4-0952-4b9f-bb21-c53c99b31257)

Your description on how to reproduce however differs from what you wrote in the title, so maybe I got it wrong? Please try to reproduce with the `ecal_sample_person_snd_tcp`, as that sample is available to us.
