### ISSUE TITLE
Extendable python subscriber callback function signature

### ISSUE THREAD

**Issue by afri-bit** [eclipse-ecal/ecal#1277]
### Context

Currently the python callback function signature has a fix signature, that cannot be extended with optional arguments. Sometimes we want to have another parameters from our application to be passed and use them upon processing the incoming message. 
Therefore an extendable callback function would be helpful in this particular cases.

### Proposal

```python
# Set callback
subscriber.set_callback(callback, (arg1, arg2, ...))

# Callback function
def callback(topic_name, msg, time_stamp, arg1, arg2, ...):
    ...
```

**Comment by DownerCase** [comment]
You can do this with [functools.partial](https://docs.python.org/3/library/functools.html#functools.partial)!

Eg:
```
def my_function(arg1, arg2, topic_name, data, clock):
    ...

callback = functools.partial(my_function, my_arg1, my_arg2)
client.add_response_callback(callback)
```

I've used this method to pass extra data into a service client.

**Comment by afri-bit** [comment]
I guess that will do the trick :)
Thanks for very quick response 👍
