### ISSUE TITLE
QT_DIR issues with Qt6

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#1374]
@rex-schilasky reported issues to find Qt6.

**Comment by FlorianReimold** [comment]
Which version are you building with? I am pretty sure that 6.2 will not work anyways, as Qt6 wasn't feature complete back then.  I only tested 6.5 and 6.6 (I read those are binary compatible).

**Comment by rex-schilasky** [comment]
My last feedback needs to be corrected. I tested with 6.6.2.

**Comment by FlorianReimold** [comment]
@rex-schilasky  Can you please give more detailed informationon your system?

- eCAL version / commit
- CMake Version
- List of installed Qt Versions
- CMake options for building eCAL
