### ISSUE TITLE
ecal.core.core.mon_monitoring() and mon_pubmonitoring() improperly parsing binary data

### ISSUE THREAD

**Issue by 66hades** [eclipse-ecal/ecal#1405]
### Problem Description

When I use mon_monitoring() [ecal.core.core module — Eclipse eCAL™ (eclipse-ecal.github.io)](https://eclipse-ecal.github.io/ecal/_api_python/ecal.core.core.html#ecal.core.core.mon_monitoring) and mon_pubmonitoring() [ecal.core.core module — Eclipse eCAL™ (eclipse-ecal.github.io)](https://eclipse-ecal.github.io/ecal/_api_python/ecal.core.core.html#ecal.core.core.mon_pubmonitoring) I expect that it would publish a message’s contents in the key ‘tdesc’. When the contents are binary format, It only takes two bytes of data, and cuts out the remainder. This is a problem for people using the function with binary messages because it reports incomplete data.

### How to reproduce

1. Execute the function `X.mon_monitoring()` 
example excerpt output from `X.mon_monitoring()` : 
```
'dclock': 1020535,
'dfreq': 15759842,
'direction': 'publisher',
'hname': 'something_generic',
'pid': 165476,
'pname': 'C:\\Program Files (x86)\\ecal_play_gui.exe',
'rclock': 3,
'tdesc': b'\x00',
'tid': '221785844831500',
'tname': 'Gateway_RadarSensorHealth',
'tsize': 0,
'ttype': '',
'uname': 'eCALPlayGUI'},
```
example output from `X.mon_pubmonitoring()`
![image](https://github.com/eclipse-ecal/ecal/assets/9824238/aed7be4d-e787-4e20-95d5-fe29a7b3528d)

2. Compare to eCAL monitor's output
![image](https://github.com/eclipse-ecal/ecal/assets/9824238/37629477-3df5-4e41-836f-d74eb6b15454)

Example binary message:
[binary_messages.zip](https://github.com/eclipse-ecal/ecal/files/14437805/binary_messages.zip)

### How did you get eCAL?

Download from Release Page

### Environment

- ecal5                    5.10.1
![image](https://github.com/eclipse-ecal/ecal/assets/9824238/db7301bc-2905-4b27-9e0a-56d49bd15e67)
- windows 10 enterprise
- Python 3.10.5
-

**Comment by 66hades** [comment]
I think this might be caused by the `\x` character somehow?

**Comment by rex-schilasky** [comment]
Hi @66hades, 

the monitoring API provides all eCAL registration/monitoring layer (used for discovery) except the message content (payload in case of a pub/sub, request or respond in case of services). It just contains all kind of runtime attributes of the eCAL entities process, publisher, subscriber and service.

The `tdesc` field is the so called topic description that is - together with the topic type and encoding - needed to deserialize a payload content that is encoded with any kind of serialization technique.

**Comment by 66hades** [comment]
Ah, thank you for the detailed response, I appreciate it 😊

**Comment by 66hades** [comment]
@rex-schilasky that link send broken, and some of the documentation pages are blank, is there an issue with the online documentation?

**Comment by rex-schilasky** [comment]
@66hades I can't find any issue with the documentation. Can you provide some more details please?

**Comment by 66hades** [comment]
> @66hades I can't find any issue with the documentation. Can you provide some more details please?

The specific function "pub_set_description" is not documented on that page, and not found in the repository.

Also, the publisher webpage is blank, contains no information
![Screenshot_20240314_140615_Chrome.jpg](https://github.com/eclipse-ecal/ecal/assets/9824238/dfc341b1-f712-4f0f-8e0c-c121a784edf5)

![Screenshot_20240314_140631_Chrome.jpg](https://github.com/eclipse-ecal/ecal/assets/9824238/a797b3ce-fca7-47a0-9cfd-96af2db5c4ba)

**Comment by rex-schilasky** [comment]
Hi, we will check this next week. The python / C and C++ API's are in redesign phase for upcoming eCAL6 on master branch. The online documentation is based on that branch unfortunately and could be broke in some way.

Regarding `pub_set_description` .. this function won't be available anymore in eCAL6. Descriptor and type names has to be defined in the publisher constructor. See

https://eclipse-ecal.github.io/ecal/_api_python/ecal.core.core.html#ecal.core.core.pub_create
