### ISSUE TITLE
How to solve inter process communication timeout in ecal

### ISSUE THREAD

**Issue by a2576014760** [eclipse-ecal/ecal#1465]
### Problem Description

When I use semaphores to control communication between two processes, there is always a problem of information not being transmitted.

### How to reproduce

I don't know_

### How did you get eCAL?

Download from Release Page

### Environment

linux C++

### eCAL System Information

```text
The latest source code used
```

**Comment by FlorianReimold** [comment]
I have no idea what this issue is about.
