### ISSUE TITLE
eCAL Monitor, "Error getting Monitoring Information"

### ISSUE THREAD

**Issue by brucehking** [eclipse-ecal/ecal#1497]
### Problem Description

After installing this release of eCAL v5.12.4, https://github.com/eclipse-ecal/ecal/releases/tag/v5.12.4, then running eCAL Monitor, the monitor does not see any Topics and displays "Error getting Monitoring Information". Troubleshooting this issue following these instructions https://eclipse-ecal.github.io/ecal/getting_started/monitor.html, including "turn off your firewall!" did not resolve the issue. A 'fix' was found which resolved the issue on two other computers, however, it did not resolve it on a third computer.

### How to reproduce

1. Download release from this link: https://github.com/eclipse-ecal/ecal/releases/download/v5.12.4/ecal_5.12.4-win64.exe
2. Run installer.
3. Open eCAL Monitor.

4. Firewall software is managed via Trellix (see image below):

### How did you get eCAL?

Download from Release Page

### Environment

eCAL: v5.12.4
OS: Windows 10 Enterprise
Python: 

### eCAL System Information

```text
------------------------- SYSTEM ---------------------------------
Version                  : v5.12.4 (08.02.2024)
Platform                 : x64

------------------------- CONFIGURATION --------------------------
Default INI              : C:\ProgramData\eCAL\ecal.ini

------------------------- NETWORK --------------------------------
Host name                : 
Host group name          : 
Network mode             : cloud
Network ttl              : 2
Network sndbuf           : 5 MByte
Network rcvbuf           : 5 MByte
Multicast cfg version    : v1
Multicast group          : 239.0.0.1
Multicast mask           : 0.0.0.15
Multicast ports          : 14000 - 14010
Multicast join all IFs   : off
Bandwidth limit (udp)    : not limited

------------------------- TIME -----------------------------------
Synchronization realtime : "ecaltime-localtime"
Synchronization replay   :
State                    :  synchronized
Master / Slave           :  Master
Status (Code)            : "everything is fine." (0)

------------------------- PUBLISHER LAYER DEFAULTS ---------------
Layer Mode INPROC        : off
Layer Mode SHM           : auto
Layer Mode TCP           : off
Layer Mode UDP MC        : auto

------------------------- SUBSCRIPTION LAYER DEFAULTS ------------
Layer Mode INPROC        : on
Layer Mode SHM           : on
Layer Mode TCP           : on
Layer Mode UDP MC        : on
Npcap UDP Reciever       : off

------------------------- EXPERIMENTAL ---------------------------
SHM Monitoring           : off
SHM Monitoring (Domain)  : ecal_mon
SHM Monitoring (Queue)   : 1024
Network Monitoring       : on
Drop out-of-order msgs   : off
```

**Comment by KerstinKeller** [comment]
It seems you are a Continental employee, please reach out to us using internal communications.
