### ISSUE TITLE
Missing file for cmake 

### ISSUE THREAD

**Issue by cmallardm** [eclipse-ecal/ecal#1512]
### Problem Description

Im following this guide https://eclipse-ecal.github.io/ecal/development/building_ecal_from_source.html, and the step where it is supossed to be build with cmake, this occurs 

CMake Error at CMakeLists.txt:167 (find_package):
  By not providing "FindCMakeFunctions.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "CMakeFunctions", but CMake did not find one.

  Could not find a package configuration file provided by "CMakeFunctions"
  with any of the following names:

    CMakeFunctionsConfig.cmake
    cmakefunctions-config.cmake

  Add the installation prefix of "CMakeFunctions" to CMAKE_PREFIX_PATH or set
  "CMakeFunctions_DIR" to a directory containing one of the above files.  If
  "CMakeFunctions" provides a separate development package or SDK, be sure it
  has been installed.
  
  Although the file is there, it is not recognized thirdparty/cmakefunctions/cmake_functions/cmake/CMakeFunctionsConfig.cmake.in
  
### How to reproduce

Guess trying to build for ubuntu 22.04

### How did you get eCAL?

Custom Build / Built from source

### Environment

Ubuntu 22.04
cmake 3.22.1

**Comment by KerstinKeller** [comment]
Hi @cmallardm,

We have recently modified eCAL to user CMake dependency providers, e.g. this means that the user is responsible to provide all dependencies, or pass `-DCMAKE_TOP_LEVEL_INCLUDES=cmake/submodule_dependencies.cmake`.

However, please don't work on master. Please use our latest release 5.12.4 (branch: support/v5.12, tag: v5.12.4) if you're building from source, or our RC branch for 5.13. (branch support/v5.13). The master branch is currently work in progress as a preparation for eCAL 6.

On these branches, the build should work out-of-the box.

**Comment by cmallardm** [comment]
Awesome. Initially, I resolved this by working with a previous commit of the master branch that a teacher had tested weeks ago and suggested I work with it. As expected, it worked.

And with this new information, ill be working with the mentined branches. Thanks for getting in touch

**Comment by rex-schilasky** [comment]
@cmallardm what are you using eCAL for?

**Comment by alx3416** [comment]
@rex-schilasky Hi! we are using eCAL with raspberry Pi 3 and 4 (Ubuntu 22.04) for a college curse oriented to services and internet of things, we found useful eCAL to work with protocol buffers to send/receive data and video in real time

So for the sake of this issue, as @KerstinKeller mentioned we'll be resorting to only release branches
