### ISSUE TITLE
Ftxui (console) based eCAL Mon CLI (htop for eCAL!)

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#494]
**Is your feature request related to a problem? Please describe.**

At the moment, have 2 eCAL Mon applications:

  1. The eCAL Mon GUI, which is feature rich and easy to use

  2. The eCAL Mon CLI, which has basically no features (at least it feels like that 😉), cannot be used from scripts (due to its blocking behaviour) and just overall feels unfinished and not well thought through.

So the latter one is the one we should improve. Especially if we more and more target headless machines and embedded systems, there really is a need for a proper eCAL monitor that can directly run on those systems. 

**Describe the solution you'd like**

An eCAL Monitor that has 2 main modes:

- A classic command line mode having MANY options. This mode should print a very clean STDOUT, either by default, or via an additonal parameter (`--cleanoutput` 🤔?), so this mode can also be used by other software and scripts to determine the state of anything in the eCAL network. In this mode, eCAL Mon CLI must always terminate in a forseeable (or configurable) time, so other scripts are not blocked.

- An ncurses mode for interactive use. Like htop. But for eCAL. I am sure that every developer would love such a thing. 

  ![htop-2 0](https://user-images.githubusercontent.com/11774314/151355467-298737d2-f18d-4e6a-8455-a8e02dd055d9.png)

**Comment by brakmic-aleksandar** [comment]
I would love to work on this issue! :)

**Comment by bsirang** [comment]
I like this!

**Comment by brakmic-aleksandar** [comment]
@Kerstin-Keller proposed to me that we could use [ftxui](https://github.com/ArthurSonzogni/FTXUI) for this task instead of ncurses.
This seems like much better solution to me (especially if we are going to support Windows), this library supports Linux/macOS/Windows and is much higher level than ncurses/pdcurses which should make code much simpler, also its quite popular.
I'll write sample app to investigate it a bit further.

**Comment by FlorianReimold** [comment]
I am open to anything, ncurses just happens to be the more popular library. The curses API has originated in the 80th though, so you probably can do much better nowadays.

**Comment by brakmic-aleksandar** [comment]
I've written [small top clone which lists processes and shows RAM usage](https://github.com/brakmic-aleksandar/bottom) to this [ftxui](https://github.com/ArthurSonzogni/FTXUI), so far I really like it, its easily extensible, contains pretty much all components (such as tables, graphs etc.) we need, and if we need something specific it shouldn't be that hard to implement, it supports mouse input and (In my opinion) functional design of library is very elegant and intuitive to work with.

**Comment by ArthurSonzogni** [comment]
@brakmic-aleksandar I was spying on who is using FTXUI and how => Happy you like it!

If in the future, you need something to be developed or fixed, please don't hesitate to ask.
There are WebAssembly examples that are worth looking to discover the existing elements.
https://arthursonzogni.com/FTXUI/examples/?file=component/homescreen

**Comment by FlorianReimold** [comment]
It's merged!
