### ISSUE TITLE
eCAL Sample for publishing Images

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#575]
For demonstration purposes it would be great to have a sample that displays Images. Basically anything is OK:

- Webcam
- Single color or color gradients
- moving eCAL Logo
- Zoom into Mandelbrot

Features:
- CLI based
- Select topic to publish to
- Select one of the above modes, if multiple modes are supported
- Select Image resolution and encoding (if possible)

Limitations:
- Only use dependencies that already exist in eCAL (if possible)
- Use some kind of standard datatype. Replicating whatever ROS does seems to be a good idea

Additions: create a Montior Plugin that can display the data

**Comment by Kerstin-Keller** [comment]
I feel like it could make sense to handle this in a separate repository, as it could be like a "big demonstrator".
It could then include datatypes (e.g. ros proto messages https://github.com/foxglove/message-schemas/tree/main/proto/ros), some samples, and the plugin.

**Comment by FlorianReimold** [comment]
This is now provided as a separate repository
https://github.com/eclipse-ecal/ecal-camera-samples


👍
