### ISSUE TITLE
Multicast groups are not updated when network interfaces change on linux

### ISSUE THREAD

**Issue by floroeske** [eclipse-ecal/ecal#695]
**Describe the bug**

Starting ecal nodes, on a machine with the main network interface down and just the loopback available, will not
start network communication when the main network interface goes up. Nodes need to manually restarted when network interfaces are up and running to get network communication going.

**To Reproduce**

***Setup***

2 Devices. Both Linux. Multicast routes for lo and main interface (enp2s0f0) are set on both devices.

```
239.0.0.0/24 dev enp2s0f0 proto static metric 1
239.0.0.0/24 dev lo proto static metric 1000
```

***Test***

Start ecal_sample_minimal_snd on one machine and ecal_sample_minimal_rec on the other with the ethernet cable unplugged.

On the machine running ecal_sample_minimal_rec. You will see the following in 'ip maddr show'. Multicast group is joined on
loopback device. Makes sense. enp2s0f0 is down.

```
ip maddr show | grep "lo\|enp2s0f0\|239.0.0"

1:      lo
        inet  239.0.0.7
        inet  239.0.0.1 users 2
2:      enp2s0f0
```

Plug cable in enp2s0f0.

```
ip maddr show | grep "lo\|enp2s0f0\|239.0.0"

1:      lo
        inet  239.0.0.7
        inet  239.0.0.1 users 2
2:      enp2s0f0
```

The subscription doesn't start. The group is still just joined on lo.

Same thing again with cable plugged in at the beginning. The group is joined on enp2s0f0
because it was up at the time and has a higher metric(?).

```
ip maddr show | grep "lo\|enp2s0f0\|239.0.0"

1:      lo
2:      enp2s0f0
        inet  239.0.0.7
        inet  239.0.0.1 users 2
```

Unplugging the cable will stop packets getting through and it resumes after plugging the cable
back in. Also ecal_mon_gui will complain about getting ecal monitoring information when it was started before the cable was unplugged.

**Expected behavior**
Network communication should start when the main network interface comes up and ecal_mon_gui shouldn't be reporting monitoring errors. Also nodes should not need to be restarted to recover communication.

**Desktop:**
 - OS: Ubuntu
 - Version 22.04

**Additional context**

I've created a workaround. So far for linux only. 

The idea was to add thread to CUDPReceiverAsio which keeps track of multicast groups and up running and running network interfaces. When groups are joined/left or network interfaces come up/go down the groups get updated.

I am guessing that 'm_socket.set_option(asio::ip::multicast::join_group(asio::ip::make_address(ipaddr_)), ec);' in  UDPReceiverAsio::AddMultiCastGroup just joins the group on one interface. I think it's the one up with the lowest metric in this case 'lo'. So when the network interfaces change the group has to be re-joined to make the communication recover.

The workaround can be found here:
https://github.com/tekniqueltd/ecal/commit/b5282a79075499992bf0747ca95511b4e91eb593

But maybe there is an easier way to deal with this?

**Comment by samsta** [comment]
Any idea what the behaviour is with a `wlan` interface? And what if you have both `wlan` and an ethernet interface, which one will have the multicast group? Is there a way to control that by setting up the routing table accordingly, in which case you workaround would have to inspect that table?

**Comment by rex-schilasky** [comment]
Hi @floroeske, this is a great bug report. Thank you for reporting. I will take a few days before we can check this. There is an ongoing eCAL project task we need to finish (and besides this .. most of the team is in vacation :-)).

**Comment by floroeske** [comment]
Thanks @rex-schilasky 

@samsta My understanding is multicast will be joined on the device with the route set to the lowest metric.

E.g.
```
ip r | grep "239.0.0"
239.0.0.0/24 dev enx007100ff2731 proto static metric 1
239.0.0.0/24 dev wlp3s0 scope link metric 100
239.0.0.0/24 dev lo proto static metric 1000
```

Starting ecal_mon_gui will join the group on enx007100ff2731.

```
ip maddr show | grep "lo\|enx007100ff2731\|wlp3s0\|239.0.0"
1:      lo
3:      wlp3s0
7:      enx007100ff2731
        inet  239.0.0.1 users 4
```

If the starting metric is the other way around. E.g.

```
ip r | grep "239.0.0"
239.0.0.0/24 dev wlp3s0 scope link metric 100
239.0.0.0/24 dev enx007100ff2731 proto static metric 200
239.0.0.0/24 dev lo proto static metric 1000
```

Starting ecal_mon_gui will join the group on wlp3s0.

```
ip maddr show | grep "lo\|enx007100ff2731\|wlp3s0\|239.0.0"
1:      lo
3:      wlp3s0
        inet  239.0.0.1 users 4
7:      enx007100ff2731
```

The workaround just deals with interfaces changing the running state at the moment. It does detect if enx007100ff2731 goes down and it will join the multicast group again on wlp3s0 according to the routing table.

It will not dynamically detect if there is a different route available without a change in the interface state.

**Comment by rex-schilasky** [comment]
Hi @floroeske we just discussed that issue in the eCAL team. So the issue appears when you change your network topology (from lan to wlan or from one adapter to another). We would like to not fix that with any additional logic inside the eCAL core but accept that behavior for now. So eCAL is not able to reconnect dynamically if your network interfaces changes at runtime.

**Comment by floroeske** [comment]
Ok, thanks @rex-schilasky. I understand it would be Linux specific logic. I think multicast works a bit different on Windows. Essentially you are right it is just a problem when the topology changes.

The use-case I am concerned about is not so much about changing between wifi and ethernet. More about that we might just have the loopback device available at boot. The main network interface might come up delayed (Some network equipment takes a while to book). Which would mean eCAL nodes could start earlier than the network interface is available. Then IPC is works fine over loopback. But to get network communication going nodes need to be restarted.

**Comment by floroeske** [comment]
I found a simpler way to join multicast groups on all interfaces. Code is much shorter and doesn't need keep any state. I've added a compile flag ECAL_JOIN_MULTICAST_ON_ALL_INTERFACES similar to ECAL_JOIN_MULTICAST_TWICE. So it's disabled by default. 

Let me know if you would consider this patch https://github.com/tekniqueltd/ecal/commit/3660356131489a7a8b16ea1b52aab5d2e152f63c.

**Comment by rex-schilasky** [comment]
We will check this change in then next tech meeting. That looks much better then now.

**Comment by rex-schilasky** [comment]
@floroeske I checked your implementation in a branch and it looks okay to me so far (some minor fixes and a real world testing is left to do). But because it's your IP, so can you please make an official PR from your fork to the ecal main repository and add either a Continental standard license header or any other copyright header with a compatible license like Apache 2.0 ?

**Comment by floroeske** [comment]
@rex-schilasky Yes, I can add some headers and create an official pull request. But I see you already created one. Was that just to get clang-tidy going?

**Comment by rex-schilasky** [comment]
@floroeske yes I just wanted to check the code quality. But except this, you should create the PR because you are the author and it feels much better to start the workflow that way :).
