### ISSUE TITLE
Potential deadlock in CSubGate

### ISSUE THREAD

**Issue by Kerstin-Keller** [eclipse-ecal/ecal#707]
CSubGate might deadlock (in combination with other lock) if some action is taken within a callback.
Atm, the complete subgate is locked during the execution time of the callback.
It would be better if the SubGate was locked only during the phase of accumulating the necessary data

CSubGate internal map should have shared_ptr of DataReaders instead of a raw pointer.
That way, copies of the DataReader pointers can be made, and the locking does not need to last the complete callback.

**Comment by KerstinKeller** [comment]
See also #1073
