### ISSUE TITLE
SHM: No data transfer when quickly switching subscribers / publishers

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#711]
**Describe the bug**
When happening, the issue looks like follows:

- A topic `topic1` is published by a random task `task1`
- Another task `task2` running on the same machine subscribes to `topic1`, but does not receive any data
- When starting `task3` which subscribes to the same `topic1`, that task gets data, while `task2` still cannot receive anything

The issue happens very sporadically.

**To Reproduce**
The issue is not properly reproducible at all. What seems to trigger the issue is:
- Quickly destroing and creating subscribers
- Having many subscribers
- Allegedly, after having a running eCAL setup for some time the issue happens more often.

Currently it can only be observed on localhost, so I assume it is SHM related.

**Desktop (please complete the following information):**
 - OS: Windows & Ubuntu
 - Version: 5.10

**Additional context**
We may have different issues here that look similar and cannot be distinguished, yet

**Comment by Kerstin-Keller** [comment]
A Dump from when this issue occured showed that topics were contained twice in "m_topic_name_datareader_map".
This suggests, that maybe, upon destroying the datareader was not removed from the map (for whatever reason). Or, it was added twice for some reason.
Maybe we should create a test with multiple subscribers of the same name.

**Comment by FlorianReimold** [comment]
I feel like maybe the fix of #714 fixes this issue, too. Can you re-try with a version containing that fix (master at the time of writing this) and see if you can reproduce it?

**Comment by KerstinKeller** [comment]
This sounds a lot like the issues we've been able to fix with #1222
