### ISSUE TITLE
When creating a Measurement object with the python package _ecal_hdf5_py is not found

### ISSUE THREAD

**Issue by Kvrepo** [eclipse-ecal/ecal#781]
I'm trying to setup eCal's python library in a docker container which runs Ubuntu 18.04. (Previously we used eCal 5.3.6, so basically we'd like to upgrade for the latest version.)

I'm installing eCal the following way:

```
add-apt-repository ppa:ecal/ecal-latest
apt install -y python3.7 python3-pip
apt-get install -y ecal
apt install -y python3-ecal5
```

I was following the documentation found here: https://eclipse-ecal.github.io/ecal/getting_started/hello_world_python.html

(I know there the recommended python version is simply python3, but for other reasons we need 3.7.)

When I check with `pip list`, I see that eCal5 is indeed installed:

```
ecal5                    5.10.1
```

However when I try to create a Measurement object I get the following error:

```
#python
Python 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ecal.measurement.measurement import Measurement
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/ecal/measurement/measurement.py", line 26, in <module>
    import ecal.measurement.hdf5 as ecal_hdf5
  File "/usr/lib/python3/dist-packages/ecal/measurement/hdf5.py", line 32, in <module>
    import ecal._ecal_hdf5_py as _ecalhdf5
ModuleNotFoundError: No module named 'ecal._ecal_hdf5_py'
```

With the previous version (5.3.6) we didn't have this error (although we built that from source).

When I list the package's library for the latest install, I see this:

```
# ll /usr/lib/python3/dist-packages/ecal
total 432
drwxr-xr-x 7 root root   4096 Aug 26 14:04 ./
drwxr-xr-x 1 root root   4096 Aug 26 14:04 ../
-rw-r--r-- 1 root root      0 May 24 09:41 __init__.py
drwxr-xr-x 2 root root   4096 Aug 26 14:04 __pycache__/
-rw-r--r-- 1 root root  74536 May 24 09:41 _ecal_core_py.cpython-36m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root 333440 May 24 09:41 _ecal_hdf5_py.cpython-36m-x86_64-linux-gnu.so
drwxr-xr-x 3 root root   4096 Aug 26 14:04 core/
drwxr-xr-x 3 root root   4096 Aug 26 14:04 measurement/
drwxr-xr-x 7 root root   4096 Aug 26 14:04 pb/
drwxr-xr-x 3 root root   4096 Aug 26 14:04 proto/
```

So the files seems to be there.

Thus I ran:

```
chmod 755 /usr/lib/python3/dist-packages/ecal/_ecal_hdf5_py.cpython-36m-x86_64-linux-gnu.so
chmod 755 /usr/lib/python3/dist-packages/ecal/_ecal_core_py.cpython-36m-x86_64-linux-gnu.so
cp /usr/lib/python3/dist-packages/ecal/_ecal_core_py.cpython-36m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/ecal/_ecal_core_py.so
cp /usr/lib/python3/dist-packages/ecal/_ecal_hdf5_py.cpython-36m-x86_64-linux-gnu.so /usr/lib/python3/dist-packages/ecal/_ecal_hdf5_py.so
```

And after removing the `cpython-36m-x86_64-linux-gnu` part of the filename plus set the `.so` files to be executables our code finally works once again.

I'm not sure however whether I've missed a step in the setup or this is an actual issue.

May I get a comment on this?

**Comment by FlorianReimold** [comment]
Hi Kvrepo,

Ubuntu 18.04's default python version is python 3.6, not 3.7. Therefore, via apt-get you can only install the 3.6 binding of eCAL. You will have the same issue with every other python package as well, via apt-get.

What you can do is simply install the `.whl` from the eCAL Downloads page:
https://eclipse-ecal.github.io/ecal/_download_archive/download_archive_ecal_5_10_2.html

There you can find bindings for other python versions as well (including 3.7 on Bionic). That should fix your issue without having to copy and rename any shared object file 😉

Best Regards
Florian

**Comment by Kvrepo** [comment]
I didn't mention this, but we've installed python 3.7 on Ubuntu 18.04 by adding the necessary repos (ppa:deadsnakes/ppa).

However reading your comment made me realize that this decision came with some unforeseen consequences.

If I switch from `bionic` to `focal` and make the transition to python 3.8 from 3.7 I can install eCal just fine with `apt install -y python3-ecal5` and everything works as intended.

Thank you very much for the fast and helpful response!

**Comment by FlorianReimold** [comment]
Switching to Focal is a good idea anyways, as Bionic will go out of support in April 2023 👍
