### ISSUE TITLE
Core: Inconsistency when adding Descriptions to `descgate`

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#782]
While working on #517 I discovered an inconsistent behavior when handling type names and type descriptors for publishers and Subscribers:

- `CPublisher::Create` properly adds the topic typename and description to the internal database (`descgate`). However, the user is allowed to leave either one or both of them two empty. If empty, they may be overwritten in the database by external data (from the current implementation).

    https://github.com/eclipse-ecal/ecal/blob/218d0625a98282a71a63f459cb8b4ef601c0288b/ecal/core/src/pubsub/ecal_publisher.cpp#L154

- `CPublisher::SetDescription` does not update the internal Descriptor database. It only sends out the description via a "Sample", i.e. it sends it out via UDP.

    https://github.com/eclipse-ecal/ecal/blob/218d0625a98282a71a63f459cb8b4ef601c0288b/ecal/core/src/pubsub/ecal_publisher.cpp#L196

- ~~`CPublisher::SetTypeName`~~ does not exist at all.

The `CSubscriber` works the same, but it doesn't support setting a description after creation at all.

@rex-schilasky Is this inconsistent behavior intended?

**Comment by FlorianReimold** [comment]
Rex told me there isn't, so I am changing it.

**Comment by rex-schilasky** [comment]
Solved with PR #783.
