### ISSUE TITLE
Raspberry Pi Support

### ISSUE THREAD

**Issue by rlewkowicz** [eclipse-ecal/ecal#785]
I'm working on building this right now, and I have no doubt this is everything I'm looking for. The project looks amazing. I'm doing a native build now (it's going to take a billion years on the pi zero lol), if it works then I can look at doing a cross compile. Lets say all this works. Just based on what this project looks like, this would be wonderful for the maker space in general. 

Whats your ci/cd tool? If I get the build working you want me to just copy pasta that here? Is anyone interested in this?

**Comment by FlorianReimold** [comment]
Thanks for the compliments!

eCAL was actively used on Raspberry Pies in the past, as we used those to test out eCAL on arm64 in general. However, I think nobody ever tried on a Pi Zero. Back then we used Ubuntu 16.04 on the Pi. Nowadays more modern Ubuntus are available. We cross-compiled eCAL for arm64 at first, but cross compiling is always a pain in the a**, so nowadays we use the Launchpad CI to natively compile the Ubuntu ARM binaries. So just in case you are also using Ubuntu on your pi zero, you should be able to add the PPA and then `apt-install ecal`.
https://eclipse-ecal.github.io/ecal/getting_started/setup.html#fa-ubuntu-automatically-install-ecal-from-a-ppa

For building on your own I recommend checking our GH Actions CI Script:
https://github.com/eclipse-ecal/ecal/blob/21eb65a7597f32ec9a8c60f6b12e919f62ec44cc/.github/workflows/build-ubuntu-22.yml#L47
and the documentation:
https://eclipse-ecal.github.io/ecal/development/building_ecal_from_source.html#fa-ubuntu-building-ecal-on-ubuntu

And sure, if you have something you want to share, just post it! Maybe it will help someone else!

**Comment by rex-schilasky** [comment]
Not really up to date anymore and unfortunately german only but maybe worth to check [build eCAL on a Raspberry Pi 3](https://www.youtube.com/watch?v=tFmzWDboKl4).

**Comment by rlewkowicz** [comment]
That's cool, I didn't realize you could do ubuntu on pi (I guess it makes sense). I'm just on raspbian. 

Overall, the the newer ubuntu build docs work as is, minus the fact that you need gcc 8 and g++ 8 (gcc-8 and g++-8 respectively) or else you run into linker errors that will send you down red herring rabbit holes.
