### ISSUE TITLE
Documentation: Properly sort Python bindings by version

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#793]
Currently, the Python bindings seem to be sorted  by name in the Download section:

![image](https://user-images.githubusercontent.com/11774314/190399984-11d851dd-812b-409c-a594-79de5d097bca.png)

It would be much nicer to sort it by version number and move the 3.10 binding to the bottom.

**Comment by KerstinKeller** [comment]
How about move 3.10 to the top, e.g. sort by most recent to least recent 😉

**Comment by FlorianReimold** [comment]
Fair point, maybe that's even better!
