### ISSUE TITLE
eCAL::message Intended usage and Extension

### ISSUE THREAD

**Issue by chengguizi** [eclipse-ecal/ecal#799]
Hi eCAL team,

I would like to know more about the intention of `eCAL::message`, found for example here:
https://github.com/eclipse-ecal/ecal/blob/master/contrib/message/include/ecal/msg/proto/message.h

1. Currenly seems only hdf5 related codebase is using it. Is it intended to be used in a more generic way? Or more like a eCAL internal thing (set of helper functions) that we shall safely ignore?
2. I can see only protobuf and string versions are implemented. What will flatbuffers and capnproto miss out in this case? (some hdf5 related functionalities, like recording?) 

I am trying to see if there is a need to extend this API, if I want to use capnproto as the primary protocol.

Thanks!

**Comment by FlorianReimold** [comment]
@KerstinKeller: Do you know, why we have the [contrib/message](https://github.com/eclipse-ecal/ecal/tree/master/contrib/message) directory while also having the [ecal/core/include/msg/](https://github.com/eclipse-ecal/ecal/tree/master/ecal/core/include/ecal/msg) directory?

Is this due to some kind of compatiblity? or is the contrib/message directory some kind of started-but-never-finished feature?

**Comment by KerstinKeller** [comment]
[ecal/core/include/msg/](https://github.com/eclipse-ecal/ecal/tree/master/ecal/core/include/ecal/msg) implements only the publishers / subscribers / client / server version for the different language protocols.

[contrib/message](https://github.com/eclipse-ecal/ecal/tree/master/contrib/message) on the other hand is thought to provide an interface that can be implemented for a given serialization format to allow for thourough support of that serialization format throughout ecal.
However, as of now, it is only used in the context of the high level measurement interface, but ideally the user needs to implements this interface (or parts of it), and then gets the full fledged eCAL support.
E.g. reflection in eCAL monitor, Publishers and Subscribers as well as reading back from measurements.

So, as of now, you cannot use the high level measurement interface for reading back your measurements and directly extracting Flatbuffer / Capnproto objects.
So for example we only have a Capnproto reflection monitor plugin, but not one for flatbuffers.
