### ISSUE TITLE
Samples: Create binary Pub/Sub sample (C++)

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#800]
# Current state

Currently, we have the minimal pub/sub samples in C++ that are not really that minimal, as they use std::string to send data and therefore use the msg/string class.
https://github.com/eclipse-ecal/ecal/tree/master/samples/cpp/minimal

This does not really reflect the "low level" C++ API that at the end just sends a memory blob by pointer and size

# Goal

The goal is to have a sample pair that sends a binary blob by **pointer** and **size**. The reason for this is to demonstrate that the user doesn't have to use a serialization format like protobuf to send anything else than an std::string.

**Comment by chengguizi** [comment]
On this line, How about the binary support on Python API as well?

Currently, there are only `StringSubscriber` and `ProtoSubscriber` implemented. I can work around to read the raw bytes by removing the `decode()` function in the  `StringSubscriber` , like this
```
  def _on_receive(self, topic_name, msg, time):
    self.callback(topic_name, msg, time)    
```

Is it desired to have `ByteSubscriber` and perhaps `CapnPotoSubscriber` etc implemented in Python API as well? I could probably work on a PR if needed, as the change seems to be pure Python.
