### ISSUE TITLE
Apps: Use Dark-Mode as default?

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#801]
# Introduction

Shall we have the dark-mode by default enabled on all eCAL Apps?
This topic is still up for discussion. Please comment on this!

# Issues

Currently, I think the eCAL Parser icon and the Open Console Icon are hard to read and may have to be revised.

![image](https://user-images.githubusercontent.com/11774314/192288425-1ccdc4b4-cfec-4deb-a950-9e40dd49eab1.png)

![image](https://user-images.githubusercontent.com/11774314/192288517-935e6882-f354-4d70-bf6f-485bfe49f841.png)

# Screenshots

![image](https://user-images.githubusercontent.com/11774314/192287558-b9d0cfa3-9c6e-42c2-b6dc-272e6d07c572.png)

![image](https://user-images.githubusercontent.com/11774314/192287576-2d5ca6ab-7765-4e21-ac3c-b0a832c292a7.png)

![image](https://user-images.githubusercontent.com/11774314/192287779-0bec6572-b5cc-4a2b-af0b-1a5cbbd3dcbe.png)

![image](https://user-images.githubusercontent.com/11774314/192288197-a8d0335d-a7c9-4a1c-a432-cbb3551e23b3.png)

![image](https://user-images.githubusercontent.com/11774314/192287817-8450010a-ba9a-4162-a3be-fae361979b31.png)

![image](https://user-images.githubusercontent.com/11774314/192287856-f1dc1f59-5ca0-43cd-a5d1-22ed1cdd283c.png)

![image](https://user-images.githubusercontent.com/11774314/192287887-2c92718e-87ef-4566-b8a7-2fe41f655829.png)

![image](https://user-images.githubusercontent.com/11774314/192288605-995849aa-0194-4251-8ba3-ad12b960de08.png)

**Comment by rex-schilasky** [comment]
YES ! Great idea.

**Comment by FlorianReimold** [comment]
Well, let's do it then!
