### ISSUE TITLE
Binary Pub/Sub Support for Python

### ISSUE THREAD

**Issue by chengguizi** [eclipse-ecal/ecal#804]
#800 Related to this, How about the binary support on Python API as well?

Currently, there are only `StringSubscriber` and `ProtoSubscriber` implemented. I can work around to read the raw bytes by removing the `decode()` function in the  `StringSubscriber` , like this
```
  def _on_receive(self, topic_name, msg, time):
    self.callback(topic_name, msg, time)    
```

Is it desired to have `ByteSubscriber` and perhaps `CapnPotoSubscriber` etc implemented in Python API as well? I could probably work on a PR if needed, as the change seems to be pure Python.

**Comment by FlorianReimold** [comment]
I just looked at the code and honestly was surprised that it didn't exist (_I am usually working on the C++ part_). I am also surprised, that nobody has ever brought it up in the past 😀
It would totally make sense to have the same low-level binary subscriber and publisher available from python and not only provide those two hardcoded message formats (Protobuf, String). Maybe one could even just implement the functions from MessageSubscriber / Publisher, that currently only raise a NotImplemented Error?

PRs highly welcome 😊

**Comment by KerstinKeller** [comment]
Actually there is a binary python subscriber. It is one level below the message subscribers, and defined in this file https://github.com/eclipse-ecal/ecal/blob/master/lang/python/core/ecal/core/core.py

You can use it directly if you need a binary subscriber.
The message subscribers just wrap the functionality.

**Comment by KerstinKeller** [comment]
No I don't think that there is a sample. In general, I am not sure if we want to encourage using the binary subscribers / publishers, though of course we could.

**Comment by FlorianReimold** [comment]
Well, it is a feature of eCAL, so why not advertise it and tell people how to use it? I didn't even know of it myself! 🤔

**Comment by chengguizi** [comment]
A very simple addition of class ByteSubscriber. I think not really worth a PR, so just to put the patch here for consideration :)

```patch
diff --git a/lang/python/core/ecal/core/publisher.py b/lang/python/core/ecal/core/publisher.py
index 3c1b8a58..ce5ee6bb 100644
--- a/lang/python/core/ecal/core/publisher.py
+++ b/lang/python/core/ecal/core/publisher.py
@@ -106,6 +106,17 @@ class StringPublisher(MessagePublisher):
   def send(self, msg, time=-1):
     return self.c_publisher.send(msg.encode(), time)
 
+class BytePublisher(MessagePublisher):
+  """Specialized publisher that sends out raw bytes
+  """
+  def __init__(self, name):
+    topic_type = "base:byte"
+    topic_desc = b""
+    super(BytePublisher, self).__init__(name, topic_type, topic_desc)
+
+  def send(self, msg, time=-1):
+    return self.c_publisher.send(msg, time)
+
 
 if __name__ == '__main__':
   """Test the publisher API
diff --git a/lang/python/core/ecal/core/subscriber.py b/lang/python/core/ecal/core/subscriber.py
index 1fa0bb8a..9f9ec543 100644
--- a/lang/python/core/ecal/core/subscriber.py
+++ b/lang/python/core/ecal/core/subscriber.py
@@ -174,6 +174,43 @@ class StringSubscriber(MessageSubscriber):
   def _on_receive(self, topic_name, msg, time):
     self.callback(topic_name, msg.decode(), time)    
 
+class ByteSubscriber(MessageSubscriber):
+  """Specialized publisher subscribes to raw bytes
+  """
+  def __init__(self, name):
+    topic_type = "base:byte"
+    super(ByteSubscriber, self).__init__(name, topic_type)
+    self.callback = None
+
+  def receive(self, timeout=0):
+    """ receive subscriber content with timeout
+
+    :param timeout: receive timeout in ms
+
+    """
+    ret, msg, time = self.c_subscriber.receive(timeout)
+    return ret, msg, time
+
+  def set_callback(self, callback):
+    """ set callback function for incoming messages
+
+    :param callback: python callback function (f(topic_name, msg, time))
+
+    """
+    self.callback = callback
+    self.c_subscriber.set_callback(self._on_receive)
+
+  def rem_callback(self, callback):
+    """ remove callback function for incoming messages
+
+    :param callback: python callback function (f(topic_name, msg, time))
+
+    """
+    self.c_subscriber.rem_callback(self._on_receive)
+    self.callback = None
+
+  def _on_receive(self, topic_name, msg, time):
+    self.callback(topic_name, msg, time)    
 
 if __name__ == '__main__':
   """Test the subscriber API
```

**Comment by FlorianReimold** [comment]
As Kerstin mentioned, there already is a binary publisher / subscriber API. We just need a sample for that, so the user can learn about it more easily.
