### ISSUE TITLE
eCAL Mon is not installed

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#824]
**Describe the bug**
The new eCAL Mon TUI is not packed into the eCAL Setup. The issue exists on Windows and Linux.

**Comment by KerstinKeller** [comment]
It seems that it is missing the install instructions.
`ecal_install_app`
see e.g. ecal_play
https://github.com/eclipse-ecal/ecal/blob/0a15d5b7c55a23b4a6f479338d8cc59416b3b405/app/play/play_cli/CMakeLists.txt#L63
