### ISSUE TITLE
FTXUI fails to compile

### ISSUE THREAD

**Issue by floroeske** [eclipse-ecal/ecal#830]
**Describe the bug**
The third_party dependency FTXUI fails to compile.

**To Reproduce**
1. git clone https://github.com/eclipse-ecal/ecal
2. git submodule init && git submodule update
3. cd ecal && mkdir _build && cd _build
4. cmake .. -DCMAKE_BUILD_TYPE=Release -DECAL_THIRDPARTY_BUILD_PROTOBUF=OFF -DECAL_THIRDPARTY_BUILD_CURL=OFF -DECAL_THIRDPARTY_BUILD_HDF5=OFF -DECAL_THIRDPARTY_BUILD_QWT=OFF
5. make VERBOSE=1
7. Build fails with:
```
[  1%] Building CXX object thirdparty/ftxui/CMakeFiles/dom.dir/src/ftxui/dom/automerge.cpp.o
cd /tmp/ecal/_build/thirdparty/ftxui && /usr/bin/c++  -I/tmp/ecal/thirdparty/ftxui/include -I/tmp/ecal/thirdparty/ftxui/src -O3 -DNDEBUG   -Wall -Wextra -std=c++14 -Wall -Wextra -pedantic -Werror -Wmissing-declarations -Wdeprecated -Wshadow -MD -MT thirdparty/ftxui/CMakeFiles/dom.dir/src/ftxui/dom/automerge.cpp.o -MF CMakeFiles/dom.dir/src/ftxui/dom/automerge.cpp.o.d -o CMakeFiles/dom.dir/src/ftxui/dom/automerge.cpp.o -c /tmp/ecal/thirdparty/ftxui/src/ftxui/dom/automerge.cpp
In file included from /tmp/ecal/thirdparty/ftxui/include/ftxui/dom/elements.hpp:162,
                 from /tmp/ecal/thirdparty/ftxui/src/ftxui/dom/automerge.cpp:4:
/tmp/ecal/thirdparty/ftxui/include/ftxui/dom/take_any_args.hpp: In function ‘ftxui::Elements ftxui::unpack(Args ...)’:
/tmp/ecal/thirdparty/ftxui/include/ftxui/dom/take_any_args.hpp:27:33: error: fold-expressions only available with ‘-std=c++17’ or ‘-std=gnu++17’ [-Werror]
   27 |   (Merge(vec, std::move(args)), ...);
      |                                 ^~~
```

**Expected behavior**
Should build.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04
 - gcc 11.2.0

**Additional context**
It seems that the "-std=c++14" compiler flag is populated all the way through to ftxui from the ecal main CMakeLists.txt.
Removing the two lines make it compile successfully.
```
  set(CMAKE_CXX_STANDARD 14)
  add_definitions(-Wall -Wextra -std=c++14)
```

I am wondering why it doesn't fail in the github pipelines.

**Comment by FlorianReimold** [comment]
I tried it on a fresh Ubuntu VM and encountered the same issue. Thanks for reporting 👍

> I am wondering why it doesn't fail in the github pipelines.

I am puzzled, too. It neither shows that issue on GH Actions nor on my main development Ubuntu 22.04.

**Comment by KerstinKeller** [comment]
I recommend that we remove / modify 
https://github.com/eclipse-ecal/ecal/blob/f87f8242db312d62743c0b406cc90b856a7ad912/CMakeLists.txt#L59-L60
Also `-Wall`,  `-Wextra` should not be forced on users.

Instead I propose to add to `mon_cli`
```
target_compile_features(foxglove_websocket PRIVATE cxx_std_17)
```
and to the other ones whatever they need (e.g C++14) (`PUBLIC` / `PRIVATE` depending on if they are a lib / executable, ...)

```
target_compile_features(foxglove_websocket PUBLIC cxx_std_14)
```

**Comment by FlorianReimold** [comment]
I removed the hardcoded C++14 settings in  PR #832. I didn't set the target compile features, as there is a pending Refactoring PR (#829) that we should merge first.
