### ISSUE TITLE
eCALSys GUI can not evaluate bash like commands

### ISSUE THREAD

**Issue by ishansheth** [eclipse-ecal/ecal#847]
**Describe the solution you'd like**
In eCALSys GUI, there is a editbox called "Algo:" to provide the executable name.
In this box, only name of the executable with path can be entered 
_e.g. /home/eCAL/send_message_

But I have a usecase where in would like to redirect the output of the executable in a log file
_e.g. /home/eCAL/send_message >> /home/log/messages.txt_
which is not possible. When i entered as shown above, eCALSys i searching executable with a name
 "send_message >> /home/log/messages.txt" instead of "send_message". So its taking the entire last
stub as an executable name which does not exist and I see the error message on console.

Is it possible to have this feature in linux where I can provide such redirection or pipe to other command? The string entered
in the box needs to be evaluated as a bash command. I am not sure if this applies to windows as well in any case as i 
do not worked with windows much.

**Describe alternatives you've considered**
As an alternative, I wrote a bash script with the line "/home/eCAL/send_message >> /home/log/messages.txt"
and called used its name in the "Algo" editbox. This is doable but its not possible to kill an executable started
via bash. eCALSys can only kill the executable started by its own as far as i know.

**Comment by FlorianReimold** [comment]
Hey Ishan,

We are putting it on our roadmap, but don't expect to actually implement it any time soon. There are some challenges that have to be solved for this.

1. Bash is basically linux only. And also on Linux, bash isn't usually the default interpreter. At least on Ubuntu its `sh`. Other Unix like operating systems (like MacOS) use zhs. Windows not have bash at all and Windows users will probably not expect bash commands to work on their OS. So on Windows, a script should probably be interpreted by CMD or Powershell. But on Windows you could also think about vbs scripts, as that scripting language is pretty much baked into the OS.

    So we either have to:
    - Implement a custom (bash?) interpreter right into eCAL Sys (I strongly vote against this)
    - Make the interpreter configurable
    - Detect the default interpreter for the current OS and use that

2. A bash / sh / batch / etc. script can pretty much do whatever it wants. It's not guaranteed that it terminates after having launched its application. It's also not guarantee
that it waits until the application has terminated. It may not launch an application at all or it may launch multiple applications. There is no way of knowing or enforcing this. For displaying the task state of the launched application however we would have to assume / enforce that one and only one application is launched by the script and we have a way to discover the PID of that application. Getting the PID is not as easy as currently, where the `exec` / `CreateProcess` call return the PID.

Kind Regards
Florian

**Comment by ishansheth** [comment]
Hi Florian,
I was thinking that probably forwarding the string to bash might solve the issue. But it has the challenges as you mentioned. On top of that, there is no way of knowing what script is doing inside as you mentioned in point 2. So we can leave this issue and i can close it. 

If i can contribute in any other way then i would be glad to do it. I can solve some other issues raised by the users if you like. I have to look into code and understand but still i could contribute. 
Thanks

**Comment by ishansheth** [comment]
Hi Florain,
Ok ya, i will have a look at the mentioned issue and comment there in case i have some question to clarify.
