### ISSUE TITLE
subscriber should not unlink topic shm mutex file during it's own destroying

### ISSUE THREAD

**Issue by tsingakbar** [eclipse-ecal/ecal#854]
## Describe the bug
say:
1.  publisher is publishing topic t1, which will internally created xxx_shm and xxx_shm_mtx
2.  subscirber1 subscribed t1 and consumed messages normally, then during destroying, it [unlinked](https://github.com/eclipse-ecal/ecal/blob/55d597d99a2b5aaac0f3a6954f3241d6fc6d2b3b/ecal/core/src/io/ecal_memfile.cpp#L155) xxx_shm_mtx
3.  subscriber 2 subscribed, but being unable to located xxx_shm_mtx, it will create another xxx_shm_mtx by itself, which is different than the one holding by publisher now.
4.  subscirber2 can consume message as if everthing is normal, but actually the xxx_shm's read/write is no longer exclusively guarded. 

## To Reproduce
see above

## Desktop 
OS: Ubuntu1804
version: latest master

**Comment by rex-schilasky** [comment]
Thank you @tsingakbar for the bug report. I checked the code and changed the logic from

```cpp
bool CMemoryFile::Destroy(const bool remove_)
  {
    if (!m_created) return(false);

    // return state
    bool ret_state = true;

    // destroy memory file
    ret_state &= memfile::db::RemoveFile(m_name, remove_);

    // unlock mutex
    ret_state &= DestroyMtx(&m_memfile_info.mutex);

    // cleanup mutex
    ret_state &= CleanupMtx(m_name);

    // reset states
    m_created      = false;
```

to

```cpp
  bool CMemoryFile::Destroy(const bool remove_)
  {
    if (!m_created) return(false);

    // return state
    bool ret_state = true;

    // destroy memory file
    ret_state &= memfile::db::RemoveFile(m_name, remove_);

    if (remove_)
    {
      // destroy mutex
      ret_state &= DestroyMtx(&m_memfile_info.mutex);

      // cleanup mutex
      ret_state &= CleanupMtx(m_name);
    }
    else
    {
      // unlock mutex
      ret_state &= UnlockMtx(&m_memfile_info.mutex);
    }

    // reset states
    m_created      = false;
```

so the memory file mutex is no more destroyed from a subscribers side (`remove_ == false`). In this case it's just released.

Can you please verify this solution ?

**Comment by rex-schilasky** [comment]
@tsingakbar sounds valid. I will adapt this and then retest.
