### ISSUE TITLE
support mac os build documentation

### ISSUE THREAD

**Issue by rsadhu** [eclipse-ecal/ecal#857]
hello,
i was trying to build ecal for mac os , considering support to build is there. however i ended up solving build errors and couldn't succeed.

could there be steps how to build for mac and minimal hardware and software requirements?

**Comment by FlorianReimold** [comment]
Hey Rakesh,

Take a look at our CI build script here:
https://github.com/eclipse-ecal/ecal/blob/master/.github/workflows/build-macos.yml

You don't really need Cap'n'Proto, just set `-DHAS_CAPNPROTO=OFF` in the cmake call.

Keep in mind that the MacOS Support is experimental. We are compiling on some MacOS x86_64 version on GitHub's CI (not even sure which one), so we know that it compiles. Runtime-wise it is pretty much untested, as Apple forces developers to buy proprietary hardware. And we don't have money for that at the moment ;)

Keep us updated on what you had to do to get it working 😊

Regards
Florian
