### ISSUE TITLE
Half of the frames are dropped, both in python and ecal record tool

### ISSUE THREAD

**Issue by chengguizi** [eclipse-ecal/ecal#869]
**Describe the bug**
Seems there is performance issue on streaming small packets of data. When I am streaming packets about 100 bytes, I lost consistently half of the data, no matter if I stream fast or slow. I mainly tested with python subscriber and C++ publisher. This behaviour also shows up when im using native eCAL tools.

## Case 1, streaming at 50Hz data rate:
![image](https://user-images.githubusercontent.com/7508112/200171743-55ba70c7-e214-4b37-ac57-2b0e93f96bcb.png)

## Case 2, streaming at 100Hz data rate:
![image](https://user-images.githubusercontent.com/7508112/200171776-52c25d53-e644-4bc0-9ba3-2b8f5e7cdb64.png)

## Another view in eCAL monitor & eCAL Recorder
This is another proof:
- The first half shows the publisher's stat observed in ecal monitor
- The second half shows the ecal recorder GUI instance stats. It has half the rates for small packets (motion data), normal rates for big packets (Images)

![image](https://user-images.githubusercontent.com/7508112/200171987-a45adf1c-436c-4981-ab67-b4d9a871f514.png)

**To Reproduce**
1. Publish a steady stream of small size packet ~100 bytes
2. Use ecal Monitor to confirm the frequency in Hz
3. Open up ecal recorder gui, and activate / prepare
4. You should see the recorder only receive half the rates

**Expected behavior**
The frequency should match

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Version 20.04

**Comment by chengguizi** [comment]
Im really puzzled. I cannot reproduce the same issue on a fresh minimal python / c++ publisher. The publisher is set to publish either normal string messages, or capnpropto. All seems normal. Really curious what could be the cause here..

**Comment by chengguizi** [comment]
I realise the root cause:
- I cannot send two messages back to back

To reproduce:
```
import sys
import time

import ecal.core.core as ecal_core
from ecal.core.publisher import StringPublisher

if __name__ == "__main__":
  # initialize eCAL API. The name of our Process will be "Python Hello World Publisher"
  ecal_core.initialize(sys.argv, "Python Hello World Publisher")

  # Create a String Publisher that publishes on the topic "hello_world_python_topic"
  pub = StringPublisher("hello_world_python_topic")
  
  # Create a counter, so something changes in our message
  counter = 0
  
  # Infinite loop (using ecal_core.ok() will enable us to gracefully shutdown
  # the process from another application)
  while ecal_core.ok():
    # Create a message with a counter an publish it to the topic
    current_message = "Hello World {:6d}".format(counter)
    print("Sending: {}".format(current_message))
    pub.send(current_message)
    time.sleep(1/1.e7)
    pub.send(current_message)
    
    time.sleep(0.01)
    
    counter = counter + 1
  
  # finalize eCAL API
  ecal_core.finalize()
```

If the two pub.send() are too close to each other, seems like something is getting over-written. Understand from previous discussion that there is no internal buffer in eCAL. But would this behiavour be quite undesireable.

It would probably be nicer if this ends up being blocking, to at least let the previous message go through perhaps? Some thoughts.

**Comment by rex-schilasky** [comment]
Hi @chengguizi, your messages get dropped if they can not processed on the subscriber side in less then `time.sleep(1/1.e7)`. This is because eCAL is not queuing at all and if you subscriber callback is not accessible (still processing the previous message) the publisher will overwrite the memory file with the next message.

But I'm pretty sure that corruption is not possible. Maybe you process your message in a second thread and did not protect your data by a mutual exclusion ?

You can get a blocking publication if you activate the shared memory handshake mechanism, there is unfortunately still a very small issue in the current release but anyway this should reduced your drops remarkable. See issue #858.

**Comment by rex-schilasky** [comment]
Here I found a classical sample producing a data race (aka corrupted message) ;-)

```python
import ecal.core.core as ecal_core
from byte_subscriber import ByteSubscriber

imshow_map = {}

# this thread is called by eCAL and writing on 'imshow_map'
def callback(topic_name, msg, ts):
    mat = np.zeros((800,600))
    imshow_map["mono8"] = mat

def main():  
    # initialize eCAL API
    ecal_core.initialize(sys.argv, "test_image_sub")

    # create subscriber and connect callback
    sub = ByteSubscriber("S0/camd")
    sub.set_callback(callback)
    
    # main thread is reading unprotected 'imshow_map'
    while ecal_core.ok():
        for im in imshow_map:
            cv2.imshow(im, imshow_map[im])
        cv2.waitKey(3)
    
    # finalize eCAL API
    ecal_core.finalize()

if __name__ == "__main__":
    main()
```

**Comment by rex-schilasky** [comment]
Regarding the corrupted message buffer .. can you please provide a minimal sample from the receiver logic ?

**Comment by chengguizi** [comment]
Hi @rex-schilasky ,

Thanks for the quick reply! Regarding the receiver callback is not accessible (still processing). I wonder what is the expected turn around time currently, even in C++.

For one thing, im running the python reproduction code. and open both eCAL monitor and eCAL recorder. I can already see frame drops

![image](https://user-images.githubusercontent.com/7508112/200206804-69f097fb-9281-4c2a-a6d3-0b8cb81815fe.png)

So I guess even the direct reading (not yet saving to disk, as i only activate the recorder but not saving yet), take longer than 1e-7 sec, which is 0.1usec?

**Follow-up**: I increase the delay to 1e-6 / 1e-5 sec, and there are still frame drops. At 1e-4 sec (0.1ms), the drops almost disappears, but not to zero. There might still be short burst of drops observed every now and then. This seems quite concerning, with everything the default setting.

**Comment by chengguizi** [comment]
@rex-schilasky  Setting `memfile_ack_timeout       = 10` works like a charm! May i understand the if the unit is in millisecond?

https://eclipse-ecal.github.io/ecal/configuration/options.html#cmdoption-arg-memfile_ack_timeout

**Comment by chengguizi** [comment]
I also realise an interesting (undocumented?) setting `memfile_buffer_count`. Would increasing that allow multiple copies of message stay in the publisher?

**Comment by rex-schilasky** [comment]
Btw. the shared memory layer features are documented [here](https://eclipse-ecal.github.io/ecal/advanced/layers/shm.html).
