### ISSUE TITLE
C++ send uchar over ecal without serialization (protobuf, flatbuffers etc)

### ISSUE THREAD

**Issue by rlewkowicz** [eclipse-ecal/ecal#879]
I don't see anything that explicit says I can't ask questions here. Apologies if this is misplaced. 

I just want to send a byte array of cv mat data (https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#a4d33bed1c850265370d2af0ff02e1564). I tried flatbuffers, asked over there, the responses are like doing 2 levels of reinterpret casts etc, didn't even work for me. I don't need the dimensions or any of that. Just plain ol cv mat data is the only thing im trying to send.

I guess that's my frustration with all the serialization libraries. The simple use cases work fine, I use ecal and protobuf to send some ints, and that's easy. But I still can't find any succinct example of just "heres some simple bytes, I want them to be simple bytes on the other side". Flatbuffers is like convert to uint or something I don't even fully recall. It's all esoteric and convoluted multi level type conversions that I'm having trouble wrapping my head around. 

Is there a simple way to send just raw bytes?

**Comment by rlewkowicz** [comment]
Ok, so all that flat buffer work I did, probably worked just fine actually. I'm just an idiot. I didn't have a wait key for open cv and I thought the data was corrupt. I've probably been skinning the same horse a thousand different ways.

**Comment by rex-schilasky** [comment]
Hi @rlewkowicz there are also 2 samples in the eCAL repository sending and receiving binary blobs. See https://github.com/eclipse-ecal/ecal/blob/master/samples/cpp/binary/binary_snd/src/binary_snd.cpp for sending,
