### ISSUE TITLE
Q: How is reading from a Service TCP Socket handled in eCAL?

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#905]
This question is about how the data-read from the TCP Socket is handled in eCAL, when a service has been called. So I am talking about the **Service Server** side.

First of all: here is a screenshot of a call stack:
![image](https://user-images.githubusercontent.com/11774314/206238854-f2693b36-82c1-4279-af68-ac93c2a39d14.png)

This question explicitly goes to @rex-schilasky. Please confirm or correct me, if I am wrong.

# My understanding

From what I understand, the logic is as follows:

1. A random number of bytes is read from the Socket
    https://github.com/eclipse-ecal/ecal/blob/d78e95b1c27dd99872474d6ba9b4c382c9013c78/ecal/core/src/service/asio_server.h#L54-L60

2. If there is a callback, the data is added to a member variable. I think there always is a request callback.
    https://github.com/eclipse-ecal/ecal/blob/d78e95b1c27dd99872474d6ba9b4c382c9013c78/ecal/core/src/service/asio_server.h#L78-L82
    https://github.com/eclipse-ecal/ecal/blob/d78e95b1c27dd99872474d6ba9b4c382c9013c78/ecal/core/src/service/asio_server.h#L170

3. It is checked if there is any more data available on the socket. If there is, again a random number of bytes is read. The data is added to the `request_` variable forever or until all currently available bytes are read
    https://github.com/eclipse-ecal/ecal/blob/d78e95b1c27dd99872474d6ba9b4c382c9013c78/ecal/core/src/service/asio_server.h#L84-L91

4. If there are no more bytes available, the callback is executed with whatever has been accumulated since the last call. Then the accumulated `request_` is cleared.
   https://github.com/eclipse-ecal/ecal/blob/d78e95b1c27dd99872474d6ba9b4c382c9013c78/ecal/core/src/service/asio_server.h#L98-L99

# The issue

If it is true what I wrote here, the Service API is inherently unstable and unsafe
- There seems to be no protocol involved telling how many bytes a message has
- Multiple messages can stack up in the TCP buffer and are interpreted as one contiguous message. There is no way of knowing.
- The pure absense of data is immediatelly interpreted as "end-of-message". The code always requests a random number of bytes from the socket, so when the TCP Stream is empty e.g. because an ethernet frame has been delayed or had to be re-transmitted, the message is cut into pieces and the next chunks are interpreted as their own messages or are used to prefix the next message, that may then be available.

**Comment by KanonWY** [comment]
The above problems do exist, and are relatively easy to reproduce.Just modify the [ping_client.cpp](https://github.com/eclipse-ecal/ecal/blob/master/samples/cpp/services/ping_client/src/ping_client.cpp) and it can be reproduced quickly.
1、increase ping message size to `64 * 1024` 
```cpp
//ping_client.cpp
      std::string req;
      req.resize(64*1024,'c');
//      ping_request.set_message("PING");
      ping_request.set_message(req);
```
2、delete the sleep function or increate send frequency
```cpp
//ping_client.cpp
    // sleep a second
//    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
``` 
now, start server and client. The following output information appears.
```bash
-> % ./ecal_sample_ping_server 
ping service::CServiceServerImpl::RequestCallback failed to parse request message
ping service::CServiceServerImpl::RequestCallback failed to parse request message
ping service::CServiceServerImpl::RequestCallback failed to parse request message
ping service::CServiceServerImpl::RequestCallback failed to parse request message
ping service::CServiceServerImpl::RequestCallback failed to parse request message
ping service::CServiceServerImpl::RequestCallback failed to parse request message
ping service::CServiceServerImpl::RequestCallback failed to parse request message
ping service::CServiceServerImpl::RequestCallback failed to parse request message
ping service::CServiceServerImpl::RequestCallback failed to parse request message
ping service::CServiceServerImpl::RequestCallback failed to parse request message
```
