### ISSUE TITLE
Unreliable RPC calls with large messages

### ISSUE THREAD

**Issue by floroeske** [eclipse-ecal/ecal#907]
**Describe the bug**
We are sending some long strings in protobuf RPC calls around and it seems like the calls get lost more often with increasing message size. This just seems to be happening when communicating over an ethernet network. I couldn't reproduce it on localhost communication.

I think it is related to https://github.com/eclipse-ecal/ecal/issues/905

This might also be related to https://github.com/eclipse-ecal/ecal/issues/581 but probably doesn't happen that often in a docker setup.

**To Reproduce**
1. Patch the example ping rpc application:

I have set the size of the string data to something similar we are trying to use in our application. It's really just a small base64 encoded image. The size is likely to be a bit larger in the future.

```
diff --git a/samples/cpp/services/ping_client/src/ping_client.cpp b/samples/cpp/services/ping_client/src/ping_client.cpp
index 75ab654e..06d111ed 100644
--- a/samples/cpp/services/ping_client/src/ping_client.cpp
+++ b/samples/cpp/services/ping_client/src/ping_client.cpp
@@ -51,10 +51,11 @@ int main(int argc, char **argv)
       //////////////////////////////////////
       PingRequest               ping_request;
       eCAL::ServiceResponseVecT service_response_vec;
-      ping_request.set_message("PING");
+      ping_request.set_message(std::string(25900, 'a'));
+      std::cout << "ping_request.message().size(): " << ping_request.message().size() << std::endl;
       if (ping_client.Call("Ping", ping_request, -1, &service_response_vec))
       {
-        std::cout << std::endl << "PingService::Ping method called with message : " << ping_request.message() << std::endl;
+        std::cout << std::endl << "PingService::Ping method called with message : " << ping_request.message().size() << std::endl;
 
         for (auto service_response : service_response_vec)
         {
@@ -84,7 +85,7 @@ int main(int argc, char **argv)
     }
 
     // sleep a second
-    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
+    std::this_thread::sleep_for(std::chrono::milliseconds(100));
   }
 
   // finalize eCAL API
diff --git a/samples/cpp/services/ping_server/src/ping_server.cpp b/samples/cpp/services/ping_server/src/ping_server.cpp
index 1973d57d..c87349f9 100644
--- a/samples/cpp/services/ping_server/src/ping_server.cpp
+++ b/samples/cpp/services/ping_server/src/ping_server.cpp
@@ -35,9 +35,9 @@ public:
   void Ping(::google::protobuf::RpcController* /* controller_ */, const ::PingRequest* request_, ::PingResponse* response_, ::google::protobuf::Closure* /* done_ */)
   {
     // print request and
-    std::cout << "Received request PingService / Ping     : " << request_->message() << std::endl << std::endl;
+    std::cout << "Received request PingService / Ping     : " << request_->message().size() << std::endl << std::endl;
     // create response
-    response_->set_answer("PONG");
+    response_->set_answer(std::to_string(request_->message().size()));
   }
 };
```

3. Run server and client on two different machines connected via ethernet. Set up 239.0.0.0 routes, hostsnames, etc...
4. A lot of RPC calls seem to fail. At least on my setup.  

```
~/.../bin (master)$ ./ecal_sample_ping_client
Waiting for the service ..
ping_request.message().size(): 25900
PingService::Ping method call failed ..

ping_request.message().size(): 25900

PingService::Ping method called with message : 25900
Received response PingService / Ping : 25900 from host ubuntu-X570S-UD
ping_request.message().size(): 25900

PingService::Ping method called with message : 25900
Received response PingService / Ping : 25900 from host ubuntu-X570S-UD
ping_request.message().size(): 25900
PingService::Ping method call failed ..

ping_request.message().size(): 25900
PingService::Ping method call failed ..

ping_request.message().size(): 25900
PingService::Ping method call failed ..

ping_request.message().size(): 25900

PingService::Ping method called with message : 25900
Received response PingService / Ping : 25900 from host ubuntu-X570S-UD
ping_request.message().size(): 25900
PingService::Ping method call failed ..

ping_request.message().size(): 25900

PingService::Ping method called with message : 25900
Received response PingService / Ping : 25900 from host ubuntu-X570S-UD
ping_request.message().size(): 25900

PingService::Ping method called with message : 25900
Received response PingService / Ping : 25900 from host ubuntu-X570S-UD
ping_request.message().size(): 25900
PingService::Ping method call failed ..

```

**Expected behavior**
Service calls shouldn't randomly fail.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04

**Comment by FlorianReimold** [comment]
Hey floroeske,

thank you very much for that detailed issue description. This should make it very easy for us to reproduce.

> I think it is related to https://github.com/eclipse-ecal/ecal/issues/905

If you are right (and you probably are) then exactly what I assumed in that issue will actually happen in practice and can be triggered with larger messages.
We are going to sort this out and fix it.

Kind regards
Florian

**Comment by floroeske** [comment]
Thanks @FlorianReimold . I think your assumptions in https://github.com/eclipse-ecal/ecal/issues/905 are correct. There is no encapsulation around the messages which are received by the asio server. So it's a bit random what data the server forwards to the callback.

We have seen the problem very rarely on localhost communication with larger messages as well. The problem gets worse though once you start involving a physical network and messages are big enough to be fragmented.

The solution is probably just to encapsulate the messages in a header like it's done for the UDP pub/sub https://github.com/eclipse-ecal/ecal-core/blob/2e1b46757b25c043d48f3d8e6ab326b23b59eb82/ecal/core/src/io/msg_type.h. So the server can read the header first to get the message size and then get the correct payload.

**Comment by floroeske** [comment]
My assumptions were not correct.

There is encapsulation. But just for the response. Not for the request. So large response should work fine.

Responses use STcpHeader:
https://github.com/eclipse-ecal/ecal/blob/534bc59ea19ce7a4e43c21e257420b14b362d160/ecal/core/src/service/ecal_tcpheader.h

Response size gets read in the client here:
https://github.com/eclipse-ecal/ecal/blob/42994bee5b67095c4f7aea9be13c6fded642e613/ecal/core/src/service/ecal_tcpclient.cpp#L242

And set and prepended to the data here for the server:
https://github.com/eclipse-ecal/ecal/blob/534bc59ea19ce7a4e43c21e257420b14b362d160/ecal/core/src/service/asio_server.h#L104

So I guess it's just doing the same thing for the request.

Somewhere here for the client:
https://github.com/eclipse-ecal/ecal/blob/42994bee5b67095c4f7aea9be13c6fded642e613/ecal/core/src/service/ecal_tcpclient.cpp#L180

And somewhere here for the server:
https://github.com/eclipse-ecal/ecal/blob/534bc59ea19ce7a4e43c21e257420b14b362d160/ecal/core/src/service/asio_server.h#L80
