### ISSUE TITLE
SHM Monitoring: Crashes & issues to find other processes

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#913]
This issue is about 2 (or more?) issues that seem to be related to the SHM Monitoring and maybe have the same cause. I am nevertheless describing them separately here.

The setup: 
- OS: Ubuntu 22.10 and 22.04, probably other Ubuntu Versions as well
- eCAL Version: master (probably equivalent to what will be released as 5.11.0 in a few days)
- eCAL.ini:
  - Network is turned off
  - shm monitoring is turned on
  - udp monitoring is disabled (i.e. the disabled setting is true)

# Crashes
- eCAL Play GUI replays a measurement
- Multiple eCAL Mon GUI instances are started, either from a console or from the app launcher.

Sometimes, now the eCAL Monitor crashes shortly after being started (after a second or so). The Call stack displayed by Ubuntu points to `eCAL::CMemoryFile::Create` being the issue.
![image](https://user-images.githubusercontent.com/11774314/207374882-0397d8fb-0478-4135-8c12-0c12381d934c.png)

When this issue happens, often for the other eCAL Monitors the next issue is triggered

# Cannot find the eCAL Play Process
- eCAL Play GUI replays a measurement
- Multiple eCAL Mon GUI instances are started, either from a console or from the app launcher.

After several launches (but sometimes even the first launch), either the launched eCAL Monitor or all already started eCAL Monitors fail to find the eCAL Play Process and the topics published by it. They seem to find each other just fine though.

As written, sometimes the newly started eCAL Mon causes the issue for all other already eCAL Mons as well and they recover, once that eCAL Monitor is closed.

**Comment by hannemn** [comment]
Issue has been solved and does not longer occur on Linux systems with activated shm-monitoring. For more detail see PR #917 .
