### ISSUE TITLE
[question] Force ecal to not use shm

### ISSUE THREAD

**Issue by odra** [eclipse-ecal/ecal#922]
Hello

I am trying to run ecal c++ sample apps from the docs in two different containers running in the same machine.

The containers are exposed to the host machine network but I am unable to make the subscriber app to  receive any data from the publisher app unless both containers are exposed to both IPC and PID of the host machine.

I am using the following  configuration in my `ecal.ini` file:

```ini
[publisher]
use_inproc = 0
use_shm = 0
use_tcp = 0
use_udp_mc = 2
share_ttype = 1

[network]
network_enabled           = true
multicast_ttl             = 2
shm_rec_enabled           = false
udp_mc_rec_enabled        = true
```

Is there a way to force ecal to not use shm even if both apps are running in the same machine?

**Comment by rex-schilasky** [comment]
Hi @odra,

I try to get your right. eCAL has a kind of "auto" mode to check if it should transfer data using shared memory or a network protocol like udp multicast. This is mode "2" (auto). The decision logic is quite simple. If the host names of publisher and subscriber are different it switches to shm, if not to udp multicast.

So inside your container .. do the hosts have the same name (from the underlying machine) ? If yes .. can you rename them ?

If you want to use shared memory in different containers you have to link the dev/shm from the hosting machine.

The last option you have is to force eCAL to use udp only and switch of any kind of automatic detection. To do so you need to configure the `ecal.ini` file that way.

```ini
[publisher]
use_inproc = 0
use_shm = 0
use_tcp = 0
use_udp_mc = 1            <<< use 1 instead 2 to switch of any automatic and force udp
share_ttype = 1
```

**Comment by odra** [comment]
Yes, the hosts have different hostnames, I will try to set to "1" and report my results :-)

**Comment by rex-schilasky** [comment]
Btw. there was a kind of similar question, see issue #238.

**Comment by odra** [comment]
I tried to set it to `1`but i didn't work, the sample subscriber app can't receive/read messages sent by the pblisher.

I saw that issue and I am able to make it work when exposing both IPC and and PID to the host machine but that is not an option for me.

I also have my network  routes properly set:
![Screenshot from 2022-12-19 13-22-53](https://user-images.githubusercontent.com/2183506/208472835-9bfc3974-4fb6-48cb-815e-084948219b22.png)

Would you know why does ecal need access to the PID in the host machine? Would this have something to do with /dev/shm usage?

**Comment by odra** [comment]
The first line of the subscriber app log shows the following message: `shm_open failed : /hello_world_topic_81654748045_shm errno: No such file or directory`

**Comment by rex-schilasky** [comment]
Can you please start the `sample_monitoring_reg` sample on one host and `person_snd` on the other one and check if the monitoring registration information are exchanged in the background ?

`sample_monitoring_reg` should log something like this

![image](https://user-images.githubusercontent.com/49162693/208846348-189dc3af-ff53-43d1-9405-862222ae0d9e.png)

**Comment by FlorianReimold** [comment]
Closing, as the discussion seems to be resolved.
