### ISSUE TITLE
Dotnet 4.8 4.7 and core support

### ISSUE THREAD

**Issue by uxmanz** [eclipse-ecal/ecal#931]
**Bug**
Dotnet 4.8, 4.7.x, Core is currently not supported. The Library Continental.eCAL.Core.dll fails to work with any of the stated frameworks. A nuget package may be created for easy use.

**Error**
System.BadImageFormatException: 'Could not load file or assembly 'Continental.eCAL.Core, Version=1.0.8406.16257, Culture=neutral, PublicKeyToken=null' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.'

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS 22

**Comment by FlorianReimold** [comment]
Hey uxmanz,

I am a C++ and not a C# developer, so please help to to get a kickstart into this topic.

Am I assuming correct, that
- .net is downwards compatible for binaries
- You usually want to build a lib like eCAL.Core.dll against the oldest .net Version possible
- Visual Studio contains some random version of .net that is used by default, but you can somehow also use another (e.g. older) SDK

Currently our build doesn't care about a specific .net version, it just compiles against something that is preinstalled on the GH Action runners:
https://github.com/eclipse-ecal/ecal/blob/master/.github/workflows/build-windows.yml

Maybe you have a suggestion on how we can improve that?
