### ISSUE TITLE
set_target_properties called with incorrect number of arguments

### ISSUE THREAD

**Issue by yurivict** [eclipse-ecal/ecal#932]
**Describe the bug**
```
===>  Performing out-of-source build
/bin/mkdir -p /usr/ports/net/ecal/work/.build
-- GCC detected - Adding flags
-- Module Path: /usr/ports/net/ecal/work/ecal-5.11.1/cmake;/usr/ports/net/ecal/work/ecal-5.11.1/cmake/Modules
-- Prefix Path: 
-- Content of the message: 
-- Version of this git repo: 11-eol-45116-gb58ddb1e7aeb
CMake Error at cmake/helper_functions/ecal_add_functions.cmake:149 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  cmake/helper_functions/ecal_add_functions.cmake:170 (ecal_add_shared_library)
  contrib/ecalproto/CMakeLists.txt:40 (ecal_add_library)


CMake Error at cmake/helper_functions/ecal_add_functions.cmake:158 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  ecal/pb/CMakeLists.txt:50 (ecal_add_static_library)


CMake Error at cmake/helper_functions/ecal_add_functions.cmake:149 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  ecal/core_pb/CMakeLists.txt:52 (ecal_add_shared_library)


CMake Error at cmake/helper_functions/ecal_add_functions.cmake:149 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  app/app_pb/CMakeLists.txt:57 (ecal_add_shared_library)


CMake Error at ecal/core/CMakeLists.txt:19 (project):
  VERSION ".." format invalid.
```

**Desktop (please complete the following information):**
 - OS: FreeBSD 13.1
 - Version 5.11.1

cmake-3.24.3

**Comment by yurivict** [comment]
This happens when ecal is built from a tarball, not from git clone.

**Comment by FlorianReimold** [comment]
Hey Yuri, nice to see you checking back on eCAL!

- Can you post your entire CMake Command line, so I can try replicating it?
- What "tarball" are you using? The complete `ecal-fat-source.tar.gz` including submodules, or are you stitching together your own version with the repo-only-tarball provided by github?

**Comment by yurivict** [comment]
Thanks!

It breaks because git fails to find the version.

**Comment by FlorianReimold** [comment]
Please answer the questions above, if you want us to help you.

**Comment by KerstinKeller** [comment]
eCAL uses `git describe` to figure out version information, which obviously won't work if you are building from a tarball.
What you will have to do it run CMake with a `-DECAL_BUILD_VERSION=5.y.z" to inject the version from the outside.
If you don't do it, however you should end up with eCAL version "0.0.0", which is not good, but still shouldn't produce the CMake error that you are describing.

**Comment by FlorianReimold** [comment]
seems to be resolved. Please reopen if I am wrong
