### ISSUE TITLE
-pthread is missing

### ISSUE THREAD

**Issue by yurivict** [eclipse-ecal/ecal#933]
**Describe the bug**
```
ld: error: undefined symbol: pthread_create
>>> referenced by recorder_impl.cpp
```

**Comment by FlorianReimold** [comment]
Please provide any information. We cannot help you, like that.

**Comment by yurivict** [comment]
Here is the [log](https://people.freebsd.org/~yuri/ecal-5.11.1.log).
FreeBSD 13.1

Please let me know what other info do you need.

**Comment by KerstinKeller** [comment]
So `rec_addon_core` links privately to threads:
https://github.com/eclipse-ecal/ecal/blob/73f320fde062fa1132ea569ef588366631baaee6/app/rec/rec_addon_core/CMakeLists.txt#L52-L55
and `rec_addon_dummy` (which actually causes the linker problem) also links privately to `rec_addon_core`
https://github.com/eclipse-ecal/ecal/blob/73f320fde062fa1132ea569ef588366631baaee6/app/rec/rec_addon_dummy/CMakeLists.txt#L27

Quetsion now: does `rec_addon_dummy` implicitly or explicitly creates threads, too?
https://github.com/eclipse-ecal/ecal/blob/73f320fde062fa1132ea569ef588366631baaee6/app/rec/rec_addon_dummy/src/recorder_impl.cpp#L41
It explicitly creates new threads.

So wee neew in `rec_addon_dummy/CMakeLists.txt` a 
```
find_package(Threads REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE eCAL::rec_addon_core Threads::Threads)
 ```

**Comment by KerstinKeller** [comment]
@yurivict  we saw there is now an eCAL FreeBSD port available! :+1: 🥳 

I also realized that you patched the portable endian file. 
https://cgit.freebsd.org/ports/tree/net/ecal/files/patch-lib_ecal__utils_include_ecal__utils_portable__endian.h
Is there something we can add to make it compatible with FreeBSD in general (e.g. with additional `#if` / '#elseif`?
Or even better to change it on the original file here?
https://gist.github.com/panzi/6856583#file-portable_endian-h
