### ISSUE TITLE
Mon: Don't warn for 2 or more publishers on a topic

### ISSUE THREAD

**Issue by FlorianReimold** [eclipse-ecal/ecal#936]
**Current Situation**

When opening an eCAL Mon Reflection Window, it tells you how many publishers there are on the topic you selected. For 1 publisher the note is informative, while for 0 and for 2 or more publishers it displays a warning sign.

![image](https://user-images.githubusercontent.com/11774314/211795429-ea691d07-56a5-4113-80bc-63772cb3a18c.png)

**Issue**

Having a warning for 2 or more publishers lets the user assume that eCAL has an issue with that. That is a wrong assumption. Multiple publishers for a single topic work perfectly fine and are officially supported. There isn't a reason to warn about that. Recently, this caused a confusion issue #930.

The warning was added for a specific group of users who run a specific setup where having 2 publishers on the same topic indicate a configuration issue of that specific setup. The warning however looks like an eCAL Warning and should therefore be removed.

**Solution**

Remove the warning sign and alert color (red) for 2 or more publishers and just display it as informational note.
Having a warning for 0 publishers is fine though, as the user opening a monitor reflection window will probably expect traffic going on.

**Comment by MihaiIMuraru** [comment]
implemented with #963
