### ISSUE TITLE
Version 5.11.2 installs executables and shared libraries with suffix 5.11.1

### ISSUE THREAD

**Issue by yurivict** [eclipse-ecal/ecal#946]
**Describe the bug**
For example, ```bin/ecal_launcher-5.11.1```.

**Desktop (please complete the following information):**
 - OS: FreeBSD 13.1
 - Version: 5.11.2

**Comment by FlorianReimold** [comment]
What's the expected behavior here? On Ubuntu at least you make a symlink without so-version to the shared object with so-version suffix.

**Comment by yurivict** [comment]
I have no idea why do you add version as a suffix to executables, but at least this version should match the real version.

**Comment by FlorianReimold** [comment]
> but at least this version should match the real version.

What do you mean with that? `bin/ecal_launcher-5.11.1` indicates that it comes from eCAL 5.11.1. If that is wrong, you probably forgot to pull the git tags or are specifying a wrong version number on command line.

The idea is that it enables you to have multiple versions of the same application and select the specific version by setting a symlink. For shared objects this is best practice on Linux and e.g. cpack even warns you if it finds .so files without a version suffix. Here is a screenshot from an Ubuntu 22.04 machine:
![image](https://user-images.githubusercontent.com/11774314/213997155-b6f8e963-5fbd-4261-a166-7d7ab52d31a5.png)

I admit, that it isn't that common for executables, but many (like `python`, `gcc`, `clang` etc.) still specify at least some part of their version as suffix, as it is totally reasonable to have multiple versions of those applications installed at once.

So I guess you don't do that on FreeBSD? Is there some other way of resolving version conflicts? Or is this just about the uncommon practice of suffixing an executable with the entire version?

**Comment by yurivict** [comment]
> What do you mean with that? bin/ecal_launcher-5.11.1 indicates that it comes from eCAL 5.11.1. If that is wrong, you probably forgot to pull the git tags or are specifying a wrong version number on command line.

No, I didn't forget, it pulled 5.11.2 from GitHub.

**Comment by yurivict** [comment]
> The idea is that it enables you to have multiple versions of the same application and select the specific version by setting a symlink.

This can't possibly work because it also installs headers and shared libraries without a version:
```
include/ecal/app/pb/mma/mma.pb.h
include/ecal/app/pb/play/service.pb.h
include/ecal/app/pb/play/state.pb.h
include/ecal/app/pb/rec/client_service.pb.h
include/ecal/app/pb/rec/client_state.pb.h
...
lib/libecal_rec_addon_core.so
lib/libecaltime-localtime.so
...
```

These headers and libraries would conflict between versions, so different versions can't be installed concurrently.

**Comment by FlorianReimold** [comment]
> No, I didn't forget, it pulled 5.11.2 from GitHub.

What does `git describe --tags --dirty` give you then? Because that's what is executed on build and where that version number comes from

https://github.com/eclipse-ecal/ecal/blob/34808b2bd89de94fb22b2dd522e4c2303f1feac7/thirdparty/cmake_functions/git/git_revision_information.cmake#L39

> This can't possibly work because it also installs headers and shared libraries without a version
> These headers and libraries would conflict between versions, so different versions can't be installed concurrently.

`lib/libecaltime-localtime.so` is a plugin that is loaded by name. So having a version suffix didn't work out for us. CPack complains every time that we should really add an soversion there. The lib however has a C API that didn't change for ages and is not expected to change in the future, so we should be fine nevertheless.
`lib/libecal_rec_addon_core.so` probably should have a version number. Maybe @hannemn can comment on whether there was a reason for not having one.

The headers are a different story. You don't need these headers when executing an application. So having multiple versions of the same library or application would still work.
I still have no idea how that works on FreeBSD, but on Debian-like Ubuntu distributions you would not have those headers in the "main" lib package, but create a `libecal-dev` package for those. We are currently not following this clean style for simplicity reasons.

**Comment by yurivict** [comment]
I see now.

You rely on Git to return the version. But package builder builds from the tarball and git doesn't work on a tarball.

So the version was hard-coded in the port.

Instead, you should set the version in CMakeLists.txt

**Comment by KerstinKeller** [comment]
We are not setting the version in CMakeLists.txt on purpose.
We don't have to make an additional commit to bump the version, but we just create a tag when everything is good.

As long as you build from a git repo, all is good.
If you don't build from a git repo, you have to pass in that version.

We've considered alternative approaches, e.g. to create the tarball from CMake and thus include a file with version in formation in the tarball but we didn't follow this approach...

**Comment by FlorianReimold** [comment]
We also publish a tarball with a hardcoded version for all releases. It is called `ecal-fat-source.tar.gz` and also contains the git submodules. So when using that package, you don't need `git` at all, neither for downloading source and submodules, nor for determining the version.

e.g. you can find the fat-source tarball for 5.11.2 here: https://github.com/eclipse-ecal/ecal/releases/download/v5.11.2/ecal-fat-source.tar.gz

If you check the git_revision_information.cmake from that tarball, you will see that it got patched to just return hardcoded numbers:

```cmake
function (git_revision_information)
  set(GIT_REVISION_MAJOR 5   PARENT_SCOPE)    
  set(GIT_REVISION_MAYOR 5   PARENT_SCOPE)
  set(GIT_REVISION_MINOR 11   PARENT_SCOPE)
  set(GIT_REVISION_PATCH 2  PARENT_SCOPE)
  set(GIT_DESCRIBE_TAG   "v5.11.2"      PARENT_SCOPE)
  set(GIT_REVISION_DATE  "2023-01-20 08:09:14 +0100" PARENT_SCOPE)
  set(eCAL_BUILD_DATE    "2023-01-20 08:09:14 +0100" PARENT_SCOPE)
endfunction (git_revision_information)
```

**Comment by yurivict** [comment]
Ok, thank you!
