### ISSUE TITLE
Unexpected message drops

### ISSUE THREAD

**Issue by BriFuture** [eclipse-ecal/ecal#962]
**Describe the bug**
eCAL 5.10.1 run on RaspiberryPi 4B,

the count of message sended mismatches dropped ones.

**To Reproduce**
Run programs and start ecal

**Expected behavior**

**Screenshots**
![1676041127859](https://user-images.githubusercontent.com/7582298/218123401-21da1107-8693-4a4f-bbd7-66eb100f1560.png)

**Desktop (please complete the following information):**
 - OS: [Debian 10]
 - Version [buster]

**Additional context**
Subscriber 15525 may only recieve message from publisher 15131 and no message recieved from publisher 15173 when program runs for several days.

**Comment by BriFuture** [comment]
Thank you for quick reply. 

SHM layer isuesd for interprocess communicaion.  

publisher `memfile_ack_timeout`=5 to avoid mesdage drop

So i'd expect that the counter of message dropped infomation exactly equals to 0. 

is it the best way to print each message recieved by subscriber to validate drop ?

**Comment by FlorianReimold** [comment]
> publisher `memfile_ack_timeout`=5 to avoid message drop

memfile_ack_timeout=5 tells the publisher to wait up to 5 milliseconds, until the next message is sent via SHM. If an eCAL callback does actual computation, you can easily write code that runs more than 5 milliseconds. Any message that will arrive while the callback is still running will be lost, as there is no queuing inside eCAL. If you want to have a queue, you have to create it somewhere and use the callback to push_back to it.

> is it the best way to print each message recieved by subscriber to validate drop ?

Sure, you can absolutely do that, if you are not satisfied with what the eCAL Monitor displays.

Btw, it is also a good idea to update your eCAL installation. While you could easily update to the latest 5.10 release (you are on 5.10 already, so 5.10.5 would be a drop-in replacement), I would still recommend you to update to 5.11. We did change a few things in the Memfile ACK feature with 5.11 to make it work properly, but didn't backport those changes to 5.10, as it changed the behavior.

The latest 5.11 release is [5.11.2](https://eclipse-ecal.github.io/ecal/_download_archive/download_archive_ecal_5_11_2.html). If you are using Ubuntu on your Raspi, you can [install eCAL with apt-get from the PPA](https://eclipse-ecal.github.io/ecal/getting_started/setup.html#fa-ubuntu-automatically-install-ecal-from-a-ppa) (there are arm64 binaries available)

**Comment by BriFuture** [comment]
We found that the problem exists when RTC is out of power and system didn;t get correct time until ntpd start working.

For example, it is 21:30 right now, while the raspi system time is 10:00  when booting. 

First few minutes ecal works well, but as system time jumps to 21:30, no message will be send anymore for any subscriber.

It could be reproduced by adjusting system time : `date -s "2023-02-26 21:32:00"`.

Is it a bug ? Or, is ecal driven by system time, so it is dangerous to adjust system time ?

**Comment by FlorianReimold** [comment]
Could you please update to eCAL 5.11.3, before we discuss any further? We did fix a couple of issue that could cause this and it would be a waste of time to debug the old 5.10.1 version.

**Comment by BriFuture** [comment]
Oh it's hard for us to update to 5.11.3 for our existing programs.

Emm, I'll test  eCAL 5.11.3 on one of the raspi to checkout whether it is fixed?

**Comment by FlorianReimold** [comment]
Yes, please test with the latest version.

You can also check if 5.10.6 already fixed the problem. Upgrading from 5.10.1 to 5.10.6 should be as easy as overwriting the libecal_core.so with the latest 5.10 release (those are binary compatible).
But if it doesn't fix the issue I am going to tell you to upgrade to 5.11.3 again, as we made some changes in the SHM Ack feature that may be quite relevant for you. 5.11 is still API compatible, but you may have to recompile your applications. Here is the [compatibility table](https://eclipse-ecal.github.io/ecal/versions/5.11/whats_new.html#compatibility-table) when upgrading 5.10 -> 5.11. So it's up to you which Version you are upgrading to 😉
