### ISSUE TITLE
Is callback of a subscriber running in another thread?

### ISSUE THREAD

**Issue by Roger-Sh** [eclipse-ecal/ecal#968]
Hi, 

I want to know if the callback of a ECAL subscriber is running in another thread? If I run a time-consuming process in callback (which is not recommended), will it affect the main thread?

**Comment by FlorianReimold** [comment]
Hi,

Yes, the callback is running in a separate thread and does not affect the main thread. Each subscriber has its own thread. When however new data arrives while the thread is still executing the callback, the new data is dropped. So when you are not OK with that, it may be worth the effort to use the callback thread to write the data in some kind of queue and then trigger another thread to work on the data.
With python the experience varies a little, as that language has a Global Interpreter Lock (GIL), which in certain occasions synchronizes code running in different threads.

Kind Regards
Florian
